name: Create Pull Request

description: Create a pull request for the changes that were detected

inputs:
  token:
    description: 'GitHub token'
    required: true
  title:
    description: 'Title and commit message for the PR'
    required: true
  body:
    description: 'Body of the PR'
    required: true
  branch:
    description: 'Branch name for the PR'
    required: true
  paths:
    description: 'Paths of the changes to be staged'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Create Pull Request (With Paths)
      if: inputs.paths != ''
      uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
      with:
        token: ${{ inputs.token }}
        base: main
        commit-message: ${{ inputs.title }}
        committer: GitHub <noreply@github.com>
        author: gix-bot <gix-bot@users.noreply.github.com>
        branch: ${{ inputs.branch }}
        add-paths: ${{ inputs.paths }}
        delete-branch: true
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}

    - name: Create Pull Request (Without Paths)
      if: inputs.paths == ''
      uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
      with:
        token: ${{ inputs.token }}
        base: main
        commit-message: ${{ inputs.title }}
        committer: GitHub <noreply@github.com>
        author: gix-bot <gix-bot@users.noreply.github.com>
        branch: ${{ inputs.branch }}
        delete-branch: true
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
