# .github/release-drafter.yml

name-template: 'Release v{{version}}'
tag-template: 'v{{version}}'
categories:
  - title: '🚀 Features'
    label: 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠 Maintenance'
    label: 'chore'
  - title: '🔧 Build System'
    label: 'build'
  - title: '📦 CI/CD'
    label: 'ci'
  - title: '📝 Documentation'
    label: 'docs'
  - title: '💄 Style'
    label: 'style'
  - title: '♻️ Refactoring'
    label: 'refactor'
  - title: '⚡️ Performance Improvements'
    label: 'perf'
  - title: '🧪 Testing'
    label: 'test'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## Changes

  $CHANGES  
