name: Check Backend Changes

description: Check for changes in the backend-related code and return a boolean output.

outputs:
  backend:
    description: 'True if any relevant backend file changed'
    value: ${{ steps.changes.outputs.backend }}

runs:
  using: 'composite'
  steps:
    - name: Check for changes
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: changes
      with:
        # Scripts, GitHub actions, or any path that contain 'backend' in their path.
        # The backend source code.
        # Rust files such as Cargo.lock, Cargo.toml and rust-toolchain.toml
        # The dockerfile used in this CI run, and the scripts it COPY's.
        filters: |
          backend:
            - '**/*backend*'
            - '**/*backend*/**'
            - 'src/backend/**'
            - 'src/shared/**'
            - '**/Cargo*'
            - '**/*rust*'
            - 'Dockerfile'
            - 'docker/**'
