name: Build Docker Image for E2E tests

description: An image that runs a local replica, install all required canisters and environment

inputs:
  name:
    description: Name of the image and artifact
    required: true

outputs: {}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update system packages
      run: sudo apt-get update
      shell: bash

    # We use buildx and its GitHub Actions caching support `type=gha`. For
    # more information, see
    # https://github.com/docker/build-push-action/issues/539
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build E2E Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.e2e
        cache-from: type=gha,scope=cached-stage
        cache-to: type=gha,scope=cached-stage,mode=max
        outputs: type=docker
        tags: ${{ inputs.name }}:latest

    - name: Save E2E Docker image
      run: |
        docker save ${{ inputs.name }}:latest | gzip > ./${{ inputs.name }}.tar.gz
      shell: bash

    - name: 'Upload ${{ inputs.name }}'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ./${{ inputs.name }}.tar.gz