name: Format and Commit
description: Set git remote and commit changes (e.g., formatting)

inputs:
  add:
    description: Files to add
    required: false
    default: '.'
  message:
    description: Commit message
    required: true

runs:
  using: "composite"
  steps:
    - name: Set git remote silently
      run: |
        git config --global url."https://github-actions:${{ env.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      shell: bash

    - name: Commit format
      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
      with:
        add: ${{ inputs.add }}
        default_author: github_actions
        message: ${{ inputs.message }}
