ls:
  .js: kebab-case
  .ts: kebab-case
  .svelte: PascalCase

  src/frontend/src:
    .dir: kebab-case
    .js: kebab-case
    .ts: kebab-case
    .svelte: PascalCase

ignore:
  - .dfx
  - .git
  - .idea
  - .svelte-kit
  - build
  - node_modules
  - target
  - src/frontend/src/lib/ic-pub-key
  - src/frontend/src/routes
  - src/frontend/src/tests/fixtures
