disallowed-macros = [
    { path = "std::print", reason = "Use ic_cdk::print instead" },
    { path = "std::println", reason = "Use ic_cdk::println instead" },
    { path = "std::eprint", reason = "Use ic_cdk::eprint instead" },
    { path = "std::eprintln", reason = "Use ic_cdk::eprintln instead" },
    { path = "std::assert_eq", reason = "Use pretty_assertions::assert_eq instead" },
]
disallowed-methods = [
    { path = "dfn_core::api::print", reason = "Use ic_cdk::print or ic_cdk::println instead" },
    { path = "ic_cdk::api::management_canister::ecdsa::sign_with_ecdsa", reason = "Threshold signatures may be made by the chain fusion signer only." },
    { path = "ic_cdk::api::management_canister::schnorr::sign_with_schnorr", reason = "Threshold signatures may be made by the chain fusion signer only." },
]
