/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const InitArg = IDL.Record({
		derivation_origin: IDL.Opt(IDL.Text),
		ii_canister_id: IDL.Opt(IDL.Principal),
		ecdsa_key_name: IDL.Text,
		cfs_canister_id: IDL.Opt(IDL.Principal),
		allowed_callers: IDL.Vec(IDL.Principal),
		ic_root_key_der: IDL.Opt(IDL.Vec(IDL.Nat8)),
		new_user_signups_allowed: IDL.Opt(IDL.Bool)
	});
	const Arg = IDL.Variant({ Upgrade: IDL.Null, Init: InitArg });
	const QualifiedNotificationKind = IDL.Variant({
		NoIndexCanister: IDL.Null,
		UnavailableIndexCanister: IDL.Null
	});
	const SimpleNotificationKind = IDL.Variant({
		BtcActivityInfo: IDL.Null,
		HiddenMicroTransactions: IDL.Null
	});
	const DismissedNotification = IDL.Variant({
		Qualified: IDL.Record({
			kind: QualifiedNotificationKind,
			version: IDL.Nat32,
			qualifier: IDL.Text
		}),
		Simple: IDL.Record({
			kind: SimpleNotificationKind,
			version: IDL.Nat32
		})
	});
	const AddDismissedNotificationRequest = IDL.Record({
		notifications: IDL.Vec(DismissedNotification),
		current_user_version: IDL.Opt(IDL.Nat64)
	});
	const AddDismissedNotificationError = IDL.Variant({
		TooManyNotifications: IDL.Null,
		VersionMismatch: IDL.Null,
		MaxDismissedNotifications: IDL.Null,
		UserNotFound: IDL.Null
	});
	const AddUserDismissedNotificationResult = IDL.Variant({
		Ok: IDL.Null,
		Err: AddDismissedNotificationError
	});
	const AddHiddenDappIdRequest = IDL.Record({
		current_user_version: IDL.Opt(IDL.Nat64),
		dapp_id: IDL.Text
	});
	const AddDappSettingsError = IDL.Variant({
		MaxHiddenDappIds: IDL.Null,
		VersionMismatch: IDL.Null,
		DappIdTooLong: IDL.Null,
		UserNotFound: IDL.Null
	});
	const AddUserHiddenDappIdResult = IDL.Variant({
		Ok: IDL.Null,
		Err: AddDappSettingsError
	});
	const Delegation = IDL.Record({
		pubkey: IDL.Vec(IDL.Nat8),
		targets: IDL.Opt(IDL.Vec(IDL.Principal)),
		expiration: IDL.Nat64
	});
	const SignedDelegation = IDL.Record({
		signature: IDL.Vec(IDL.Nat8),
		delegation: Delegation
	});
	const IIDelegationChain = IDL.Record({
		public_key: IDL.Vec(IDL.Nat8),
		delegations: IDL.Vec(SignedDelegation)
	});
	const AllowSigningRequest = IDL.Record({
		ii_delegation_chain: IDL.Opt(IIDelegationChain)
	});
	const AllowSigningStatus = IDL.Variant({
		Skipped: IDL.Null,
		Failed: IDL.Null,
		Executed: IDL.Null
	});
	const AllowSigningResponse = IDL.Record({
		status: AllowSigningStatus,
		allowed_cycles: IDL.Nat
	});
	const ApproveError = IDL.Variant({
		GenericError: IDL.Record({
			message: IDL.Text,
			error_code: IDL.Nat
		}),
		TemporarilyUnavailable: IDL.Null,
		Duplicate: IDL.Record({ duplicate_of: IDL.Nat }),
		BadFee: IDL.Record({ expected_fee: IDL.Nat }),
		AllowanceChanged: IDL.Record({ current_allowance: IDL.Nat }),
		CreatedInFuture: IDL.Record({ ledger_time: IDL.Nat64 }),
		TooOld: IDL.Null,
		Expired: IDL.Record({ ledger_time: IDL.Nat64 }),
		InsufficientFunds: IDL.Record({ balance: IDL.Nat })
	});
	const RateLimitError = IDL.Record({
		max_calls: IDL.Nat32,
		window_ns: IDL.Nat64,
		caller: IDL.Principal
	});
	const AllowSigningError = IDL.Variant({
		ApproveError: ApproveError,
		InvalidDelegationChain: IDL.Record({ msg: IDL.Text }),
		RateLimited: RateLimitError,
		RateLimitedByGuard: RateLimitError,
		Other: IDL.Text,
		FailedToContactCyclesLedger: IDL.Null
	});
	const AllowSigningResult = IDL.Variant({
		Ok: AllowSigningResponse,
		Err: AllowSigningError
	});
	const Network = IDL.Variant({
		mainnet: IDL.Null,
		regtest: IDL.Null,
		testnet: IDL.Null
	});
	const Outpoint = IDL.Record({
		txid: IDL.Vec(IDL.Nat8),
		vout: IDL.Nat32
	});
	const Utxo = IDL.Record({
		height: IDL.Nat32,
		value: IDL.Nat64,
		outpoint: Outpoint
	});
	const BtcAddPendingTransactionRequest = IDL.Record({
		txid: IDL.Vec(IDL.Nat8),
		ii_delegation_chain: IDL.Opt(IIDelegationChain),
		network: Network,
		utxos: IDL.Vec(Utxo)
	});
	const BtcAddPendingTransactionError = IDL.Variant({
		InvalidUtxos: IDL.Null,
		EmptyUtxos: IDL.Null,
		DuplicateUtxos: IDL.Null,
		InvalidDelegationChain: IDL.Record({ msg: IDL.Text }),
		RateLimited: RateLimitError,
		InternalError: IDL.Record({ msg: IDL.Text }),
		UtxosAlreadyReserved: IDL.Null
	});
	const BtcAddPendingTransactionResult = IDL.Variant({
		Ok: IDL.Null,
		Err: BtcAddPendingTransactionError
	});
	const BtcGetFeePercentilesRequest = IDL.Record({ network: Network });
	const BtcGetFeePercentilesResponse = IDL.Record({
		fee_percentiles: IDL.Vec(IDL.Nat64)
	});
	const BtcGetFeePercentilesError = IDL.Variant({
		InternalError: IDL.Record({ msg: IDL.Text })
	});
	const BtcGetFeePercentilesResult = IDL.Variant({
		Ok: BtcGetFeePercentilesResponse,
		Err: BtcGetFeePercentilesError
	});
	const BtcGetPendingTransactionsRequest = IDL.Record({
		ii_delegation_chain: IDL.Opt(IIDelegationChain),
		network: Network
	});
	const PendingTransaction = IDL.Record({
		txid: IDL.Vec(IDL.Nat8),
		utxos: IDL.Vec(Utxo)
	});
	const BtcGetPendingTransactionsReponse = IDL.Record({
		transactions: IDL.Vec(PendingTransaction)
	});
	const BtcGetPendingTransactionsError = IDL.Variant({
		InvalidDelegationChain: IDL.Record({ msg: IDL.Text }),
		RateLimited: RateLimitError,
		InternalError: IDL.Record({ msg: IDL.Text })
	});
	const BtcGetPendingTransactionsResult = IDL.Variant({
		Ok: BtcGetPendingTransactionsReponse,
		Err: BtcGetPendingTransactionsError
	});
	const Config = IDL.Record({
		derivation_origin: IDL.Opt(IDL.Text),
		ii_canister_id: IDL.Opt(IDL.Principal),
		ecdsa_key_name: IDL.Text,
		cfs_canister_id: IDL.Opt(IDL.Principal),
		allowed_callers: IDL.Vec(IDL.Principal),
		ic_root_key_raw: IDL.Opt(IDL.Vec(IDL.Nat8)),
		new_user_signups_allowed: IDL.Opt(IDL.Bool)
	});
	const ActiveUserTransactionRef = IDL.Record({
		key: IDL.Text,
		value: IDL.Text
	});
	const TokenId = IDL.Variant({
		Erc20: IDL.Tuple(IDL.Text, IDL.Nat64),
		ExtV2: IDL.Principal,
		SolNativeDevnet: IDL.Null,
		Icrc: IDL.Principal,
		EvmNative: IDL.Nat64,
		Icrc7: IDL.Principal,
		BtcNativeMainnet: IDL.Null,
		Erc721: IDL.Tuple(IDL.Text, IDL.Nat64),
		SolNativeMainnet: IDL.Null,
		SplDevnet: IDL.Text,
		SplMainnet: IDL.Text,
		IcpNative: IDL.Null,
		IcPunks: IDL.Principal,
		BtcNativeTestnet: IDL.Null,
		Erc1155: IDL.Tuple(IDL.Text, IDL.Nat64),
		Erc4626: IDL.Tuple(IDL.Text, IDL.Nat64),
		Dip721: IDL.Principal
	});
	const OneSecEvmToIcpData = IDL.Record({
		recipient_principal: IDL.Principal,
		source_token: TokenId,
		amount: IDL.Nat,
		dest_token: TokenId
	});
	const OneSecIcpToEvmData = IDL.Record({
		recipient_evm_address: IDL.Text,
		source_token: TokenId,
		amount: IDL.Nat,
		dest_token: TokenId
	});
	const LiquidiumAction = IDL.Variant({
		Withdraw: IDL.Null,
		Repay: IDL.Null,
		Borrow: IDL.Null,
		Supply: IDL.Null
	});
	const LiquidiumData = IDL.Record({
		token: TokenId,
		action: LiquidiumAction,
		pool_id: IDL.Text,
		amount: IDL.Nat
	});
	const ActiveUserTransactionData = IDL.Variant({
		OneSecEvmToIcp: OneSecEvmToIcpData,
		OneSecIcpToEvm: OneSecIcpToEvmData,
		Liquidium: LiquidiumData
	});
	const CreateActiveUserTransactionRequest = IDL.Record({
		id: IDL.Text,
		external_refs: IDL.Vec(ActiveUserTransactionRef),
		progress_step: IDL.Opt(IDL.Text),
		data: ActiveUserTransactionData
	});
	const ActiveUserTransactionStatus = IDL.Variant({
		Failed: IDL.Null,
		Executing: IDL.Null,
		Succeeded: IDL.Null,
		Pending: IDL.Null
	});
	const OnramperSignedEntry = IDL.Record({
		key: IDL.Text,
		value: IDL.Text
	});
	const ActiveUserTransaction = IDL.Record({
		id: IDL.Text,
		status: ActiveUserTransactionStatus,
		external_refs: IDL.Vec(OnramperSignedEntry),
		progress_step: IDL.Opt(IDL.Text),
		data: ActiveUserTransactionData,
		updated_at_ns: IDL.Nat64,
		error: IDL.Opt(IDL.Text),
		created_at_ns: IDL.Nat64
	});
	const ActiveUserTransactionError = IDL.Variant({
		InvalidId: IDL.Null,
		NotFound: IDL.Null,
		TooManyActiveTransactions: IDL.Null,
		InvalidData: IDL.Text,
		AlreadyExists: IDL.Null,
		IllegalStatusTransition: IDL.Null
	});
	const ActiveUserTransactionResult = IDL.Variant({
		Ok: ActiveUserTransaction,
		Err: ActiveUserTransactionError
	});
	const ImageMimeType = IDL.Variant({
		'image/gif': IDL.Null,
		'image/png': IDL.Null,
		'image/jpeg': IDL.Null,
		'image/webp': IDL.Null
	});
	const ContactImage = IDL.Record({
		data: IDL.Vec(IDL.Nat8),
		mime_type: ImageMimeType
	});
	const CreateContactRequest = IDL.Record({
		name: IDL.Text,
		image: IDL.Opt(ContactImage)
	});
	const BtcAddress = IDL.Variant({
		P2WPKH: IDL.Text,
		P2PKH: IDL.Text,
		P2WSH: IDL.Text,
		P2SH: IDL.Text,
		P2TR: IDL.Text
	});
	const EthAddress = IDL.Variant({ Public: IDL.Text });
	const Icrcv2AccountId = IDL.Variant({
		Account: IDL.Vec(IDL.Nat8),
		WithPrincipal: IDL.Record({
			owner: IDL.Principal,
			subaccount: IDL.Opt(IDL.Vec(IDL.Nat8))
		})
	});
	const TokenAccountId = IDL.Variant({
		Btc: BtcAddress,
		Eth: EthAddress,
		Sol: IDL.Text,
		Icrcv2: Icrcv2AccountId
	});
	const ContactAddressData = IDL.Record({
		label: IDL.Opt(IDL.Text),
		token_account_id: TokenAccountId
	});
	const Contact = IDL.Record({
		id: IDL.Nat64,
		name: IDL.Text,
		update_timestamp_ns: IDL.Nat64,
		addresses: IDL.Vec(ContactAddressData),
		image: IDL.Opt(ContactImage)
	});
	const ContactError = IDL.Variant({
		InvalidContactData: IDL.Null,
		CanisterMemoryNearCapacity: IDL.Null,
		InvalidImageFormat: IDL.Null,
		ContactNotFound: IDL.Null,
		ImageTooLarge: IDL.Null,
		TooManyContacts: IDL.Null,
		RandomnessError: IDL.Null,
		ImageExceedsMaxSize: IDL.Null,
		CanisterStatusError: IDL.Null,
		TooManyContactsWithImages: IDL.Null
	});
	const CreateContactResult = IDL.Variant({
		Ok: Contact,
		Err: ContactError
	});
	const UserAgreement = IDL.Record({
		last_accepted_at_ns: IDL.Opt(IDL.Nat64),
		text_sha256: IDL.Opt(IDL.Text),
		accepted: IDL.Opt(IDL.Bool),
		last_updated_at_ms: IDL.Opt(IDL.Nat64)
	});
	const UserAgreements = IDL.Record({
		license_agreement: UserAgreement,
		privacy_policy: UserAgreement,
		terms_of_use: UserAgreement
	});
	const ProviderAgreementProvider = IDL.Variant({ NearIntents: IDL.Null });
	const ProviderAgreementScope = IDL.Variant({ Swap: IDL.Null });
	const ProviderAgreementType = IDL.Record({
		provider: ProviderAgreementProvider,
		scope: ProviderAgreementScope
	});
	const Agreements = IDL.Record({
		agreements: UserAgreements,
		provider_agreements: IDL.Opt(IDL.Vec(IDL.Tuple(ProviderAgreementType, UserAgreement)))
	});
	const NetworkSettingsFor = IDL.Variant({
		ArbitrumMainnet: IDL.Null,
		InternetComputer: IDL.Null,
		BaseSepolia: IDL.Null,
		PolygonMainnet: IDL.Null,
		BitcoinRegtest: IDL.Null,
		SolanaDevnet: IDL.Null,
		PolygonAmoy: IDL.Null,
		EthereumSepolia: IDL.Null,
		BitcoinTestnet: IDL.Null,
		BaseMainnet: IDL.Null,
		BscMainnet: IDL.Null,
		SolanaLocal: IDL.Null,
		ArbitrumSepolia: IDL.Null,
		EthereumMainnet: IDL.Null,
		SolanaMainnet: IDL.Null,
		BitcoinMainnet: IDL.Null,
		BscTestnet: IDL.Null
	});
	const NetworkSettings = IDL.Record({
		enabled: IDL.Bool,
		is_testnet: IDL.Bool
	});
	const TestnetsSettings = IDL.Record({ show_testnets: IDL.Bool });
	const NetworksSettings = IDL.Record({
		networks: IDL.Vec(IDL.Tuple(NetworkSettingsFor, NetworkSettings)),
		testnets: TestnetsSettings
	});
	const NotificationSettings = IDL.Record({
		dismissed_notifications: IDL.Vec(DismissedNotification)
	});
	const DappCarouselSettings = IDL.Record({
		hidden_dapp_ids: IDL.Vec(IDL.Text)
	});
	const DappSettings = IDL.Record({ dapp_carousel: DappCarouselSettings });
	const ExperimentalFeatureSettingsFor = IDL.Variant({
		AiAssistantBeta: IDL.Null
	});
	const ExperimentalFeatureSettings = IDL.Record({ enabled: IDL.Bool });
	const ExperimentalFeaturesSettings = IDL.Record({
		experimental_features: IDL.Vec(
			IDL.Tuple(ExperimentalFeatureSettingsFor, ExperimentalFeatureSettings)
		)
	});
	const TransactionFilterSettings = IDL.Record({
		hide_micro_transactions: IDL.Bool
	});
	const TransactionSettings = IDL.Record({
		filter: IDL.Opt(TransactionFilterSettings)
	});
	const Settings = IDL.Record({
		networks: NetworksSettings,
		notifications: IDL.Opt(NotificationSettings),
		dapp: DappSettings,
		experimental_features: ExperimentalFeaturesSettings,
		transactions: IDL.Opt(TransactionSettings)
	});
	const UserProfile = IDL.Record({
		agreements: IDL.Opt(Agreements),
		version: IDL.Opt(IDL.Nat64),
		settings: IDL.Opt(Settings),
		created_timestamp: IDL.Nat64,
		updated_timestamp: IDL.Nat64
	});
	const CreateUserProfileError = IDL.Variant({ SignupsClosed: IDL.Null });
	const CreateUserProfileResult = IDL.Variant({
		Ok: UserProfile,
		Err: CreateUserProfileError
	});
	const DeleteActiveUserTransactionResult = IDL.Variant({
		Ok: IDL.Null,
		Err: ActiveUserTransactionError
	});
	const DeleteContactResult = IDL.Variant({
		Ok: IDL.Nat64,
		Err: ContactError
	});
	const GetActiveUserTransactionsResponse = IDL.Record({
		transactions: IDL.Vec(ActiveUserTransaction)
	});
	const GetActiveUserTransactionsResult = IDL.Variant({
		Ok: GetActiveUserTransactionsResponse,
		Err: ActiveUserTransactionError
	});
	const GetAllowedCyclesResponse = IDL.Record({ allowed_cycles: IDL.Nat });
	const GetAllowedCyclesError = IDL.Variant({
		RateLimited: RateLimitError,
		Other: IDL.Text,
		FailedToContactCyclesLedger: IDL.Null
	});
	const GetAllowedCyclesResult = IDL.Variant({
		Ok: GetAllowedCyclesResponse,
		Err: GetAllowedCyclesError
	});
	const ApiKeys = IDL.Record({
		exchange_rate_enabled: IDL.Opt(IDL.Bool),
		alchemy_api_key: IDL.Opt(IDL.Text),
		etherscan_api_key: IDL.Opt(IDL.Text),
		exchange_rate_replicated: IDL.Opt(IDL.Bool),
		coingecko_api_key: IDL.Opt(IDL.Text),
		onramper_signing_secret: IDL.Opt(IDL.Text),
		infura_api_key: IDL.Opt(IDL.Text)
	});
	const CanisterStatusType = IDL.Variant({
		stopped: IDL.Null,
		stopping: IDL.Null,
		running: IDL.Null
	});
	const DefiniteCanisterSettingsArgs = IDL.Record({
		controller: IDL.Principal,
		freezing_threshold: IDL.Nat,
		controllers: IDL.Vec(IDL.Principal),
		memory_allocation: IDL.Nat,
		compute_allocation: IDL.Nat
	});
	const CanisterStatusResultV2 = IDL.Record({
		controller: IDL.Principal,
		status: CanisterStatusType,
		freezing_threshold: IDL.Nat,
		balance: IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Nat8), IDL.Nat)),
		memory_size: IDL.Nat,
		cycles: IDL.Nat,
		settings: DefiniteCanisterSettingsArgs,
		idle_cycles_burned_per_day: IDL.Nat,
		module_hash: IDL.Opt(IDL.Vec(IDL.Nat8))
	});
	const GetContactResult = IDL.Variant({
		Ok: Contact,
		Err: ContactError
	});
	const GetContactsResult = IDL.Variant({
		Ok: IDL.Vec(Contact),
		Err: ContactError
	});
	const ExchangeData = IDL.Record({
		price_24h_change_pct: IDL.Opt(IDL.Float64),
		market_cap: IDL.Opt(IDL.Float64),
		timestamp_ns: IDL.Nat64,
		price: IDL.Opt(IDL.Float64)
	});
	const ExchangeRate = IDL.Record({ usd: ExchangeData });
	const AgreementType = IDL.Variant({
		TermsOfUse: IDL.Null,
		PrivacyPolicy: IDL.Null,
		LicenseAgreement: IDL.Null,
		Provider: ProviderAgreementType
	});
	const AgreementHistoryEntry = IDL.Record({
		timestamp_ns: IDL.Nat64,
		agreement_type: AgreementType,
		text_sha256: IDL.Opt(IDL.Text),
		accepted: IDL.Bool,
		last_updated_at_ms: IDL.Opt(IDL.Nat64)
	});
	const GetAgreementHistoryError = IDL.Variant({ UserNotFound: IDL.Null });
	const GetAgreementHistoryResult = IDL.Variant({
		Ok: IDL.Vec(AgreementHistoryEntry),
		Err: GetAgreementHistoryError
	});
	const GetUserProfileError = IDL.Variant({ NotFound: IDL.Null });
	const GetUserProfileResult = IDL.Variant({
		Ok: UserProfile,
		Err: GetUserProfileError
	});
	const GetUserTransactionsRequest = IDL.Record({
		token_id: TokenId,
		max_results: IDL.Nat64,
		start: IDL.Opt(IDL.Nat64)
	});
	const BtcTransactionData = IDL.Record({ fee: IDL.Opt(IDL.Nat) });
	const EvmTransactionData = IDL.Record({
		nft_token_id: IDL.Opt(IDL.Nat),
		data: IDL.Opt(IDL.Text),
		chain_id: IDL.Opt(IDL.Nat64),
		nonce: IDL.Opt(IDL.Nat64),
		gas_limit: IDL.Opt(IDL.Nat),
		gas_used: IDL.Opt(IDL.Nat),
		gas_price: IDL.Opt(IDL.Nat)
	});
	const SolTransactionData = IDL.Record({
		fee: IDL.Opt(IDL.Nat),
		to_owner: IDL.Opt(IDL.Text),
		from_owner: IDL.Opt(IDL.Text)
	});
	const IcrcTransactionType = IDL.Variant({
		Approve: IDL.Record({ spender: IDL.Text }),
		Burn: IDL.Null,
		Mint: IDL.Null,
		Transfer: IDL.Null
	});
	const IcrcTransactionData = IDL.Record({
		fee: IDL.Opt(IDL.Nat),
		memo: IDL.Opt(IDL.Vec(IDL.Nat8)),
		tx_type: IcrcTransactionType
	});
	const NetworkTransactionData = IDL.Variant({
		Btc: BtcTransactionData,
		Evm: EvmTransactionData,
		Sol: SolTransactionData,
		Icrc: IcrcTransactionData
	});
	const UserTransaction = IDL.Record({
		id: IDL.Text,
		to: IDL.Opt(IDL.Text),
		block_index: IDL.Nat64,
		value: IDL.Nat,
		from: IDL.Text,
		network_data: NetworkTransactionData,
		timestamp: IDL.Nat64
	});
	const GetUserTransactionsResponse = IDL.Record({
		next_start: IDL.Opt(IDL.Nat64),
		total_stored: IDL.Nat64,
		oldest_block_index: IDL.Opt(IDL.Nat64),
		newest_block_index: IDL.Opt(IDL.Nat64),
		transactions: IDL.Vec(UserTransaction)
	});
	const UserTransactionError = IDL.Variant({
		DuplicateTransaction: IDL.Record({ id: IDL.Text }),
		InternalError: IDL.Record({ msg: IDL.Text }),
		TooManyTransactions: IDL.Null,
		UserNotFound: IDL.Null
	});
	const GetUserTransactionsResult = IDL.Variant({
		Ok: GetUserTransactionsResponse,
		Err: UserTransactionError
	});
	const HasUserProfileResponse = IDL.Record({ has_user_profile: IDL.Bool });
	const HttpRequest = IDL.Record({
		url: IDL.Text,
		method: IDL.Text,
		body: IDL.Vec(IDL.Nat8),
		headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))
	});
	const HttpResponse = IDL.Record({
		body: IDL.Vec(IDL.Nat8),
		headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
		status_code: IDL.Nat16
	});
	const HttpHeader = IDL.Record({ value: IDL.Text, name: IDL.Text });
	const HttpRequestResult = IDL.Record({
		status: IDL.Nat,
		body: IDL.Vec(IDL.Nat8),
		headers: IDL.Vec(HttpHeader)
	});
	const TransformArgs = IDL.Record({
		context: IDL.Vec(IDL.Nat8),
		response: HttpRequestResult
	});
	const ErcToken = IDL.Record({
		token_address: IDL.Text,
		chain_id: IDL.Nat64
	});
	const ExtV2Token = IDL.Record({ canister_id: IDL.Principal });
	const IcrcToken = IDL.Record({
		ledger_id: IDL.Principal,
		index_id: IDL.Opt(IDL.Principal)
	});
	const SplToken = IDL.Record({
		decimals: IDL.Opt(IDL.Nat8),
		token_address: IDL.Text,
		symbol: IDL.Opt(IDL.Text)
	});
	const Token = IDL.Variant({
		Erc20: ErcToken,
		ExtV2: ExtV2Token,
		Icrc: IcrcToken,
		Icrc7: ExtV2Token,
		Erc721: ErcToken,
		SplDevnet: SplToken,
		SplMainnet: SplToken,
		IcPunks: ExtV2Token,
		Erc1155: ErcToken,
		Erc4626: ErcToken,
		Dip721: ExtV2Token
	});
	const TokenSection = IDL.Variant({ Spam: IDL.Null, Hidden: IDL.Null });
	const CustomToken = IDL.Record({
		token: Token,
		allow_external_content_source: IDL.Opt(IDL.Bool),
		section: IDL.Opt(TokenSection),
		version: IDL.Opt(IDL.Nat64),
		enabled: IDL.Bool,
		allowed_external_content_source_urls: IDL.Opt(IDL.Vec(IDL.Text))
	});
	const SaveUserTransactionsRequest = IDL.Record({
		token_id: TokenId,
		transactions: IDL.Vec(UserTransaction)
	});
	const SaveUserTransactionsResult = IDL.Variant({
		Ok: IDL.Null,
		Err: UserTransactionError
	});
	const SetShowTestnetsRequest = IDL.Record({
		current_user_version: IDL.Opt(IDL.Nat64),
		show_testnets: IDL.Bool
	});
	const UpdateAgreementsError = IDL.Variant({
		VersionMismatch: IDL.Null,
		UserNotFound: IDL.Null
	});
	const SetUserShowTestnetsResult = IDL.Variant({
		Ok: IDL.Null,
		Err: UpdateAgreementsError
	});
	const SignOnramperWidgetUrlRequest = IDL.Record({
		network_wallets: IDL.Vec(OnramperSignedEntry),
		wallets: IDL.Vec(OnramperSignedEntry),
		wallet_address_tags: IDL.Vec(OnramperSignedEntry)
	});
	const SignOnramperWidgetUrlResponse = IDL.Record({
		signature: IDL.Text,
		signed_query: IDL.Text
	});
	const SignOnramperWidgetUrlError = IDL.Variant({
		AddressMismatch: IDL.Null,
		RateLimited: RateLimitError,
		AddressDerivationFailed: IDL.Null,
		SecretNotConfigured: IDL.Null
	});
	const SignOnramperWidgetUrlResult = IDL.Variant({
		Ok: SignOnramperWidgetUrlResponse,
		Err: SignOnramperWidgetUrlError
	});
	const Stats = IDL.Record({
		active_user_transactions_count: IDL.Nat64,
		user_profile_count: IDL.Nat64,
		user_transactions_count: IDL.Nat64,
		custom_token_count: IDL.Nat64,
		exchange_rates_count: IDL.Nat64,
		token_activity_count: IDL.Nat64,
		agreement_history_count: IDL.Nat64,
		user_timestamps_count: IDL.Nat64,
		user_token_count: IDL.Nat64
	});
	const TopUpCyclesLedgerRequest = IDL.Record({
		threshold: IDL.Opt(IDL.Nat),
		percentage: IDL.Opt(IDL.Nat8)
	});
	const TopUpCyclesLedgerResponse = IDL.Record({
		backend_cycles: IDL.Nat,
		ledger_balance: IDL.Nat,
		topped_up: IDL.Nat
	});
	const TopUpCyclesLedgerError = IDL.Variant({
		InvalidArgPercentageOutOfRange: IDL.Record({
			max: IDL.Nat8,
			min: IDL.Nat8,
			percentage: IDL.Nat8
		}),
		RateLimited: RateLimitError,
		CouldNotGetBalanceFromCyclesLedger: IDL.Null,
		CouldNotTopUpCyclesLedger: IDL.Record({
			tried_to_send: IDL.Nat,
			available: IDL.Nat
		})
	});
	const TopUpCyclesLedgerResult = IDL.Variant({
		Ok: TopUpCyclesLedgerResponse,
		Err: TopUpCyclesLedgerError
	});
	const UpdateActiveUserTransactionRequest = IDL.Record({
		id: IDL.Text,
		status: IDL.Opt(ActiveUserTransactionStatus),
		external_refs: IDL.Opt(IDL.Vec(OnramperSignedEntry)),
		progress_step: IDL.Opt(IDL.Text),
		error: IDL.Opt(IDL.Text)
	});
	const UpdateProviderAgreementsRequest = IDL.Record({
		current_user_version: IDL.Opt(IDL.Nat64),
		provider_agreements: IDL.Vec(IDL.Tuple(ProviderAgreementType, UserAgreement))
	});
	const UpdateUserAgreementsRequest = IDL.Record({
		agreements: UserAgreements,
		current_user_version: IDL.Opt(IDL.Nat64)
	});
	const UpdateExperimentalFeaturesSettingsRequest = IDL.Record({
		experimental_features: IDL.Vec(
			IDL.Tuple(ExperimentalFeatureSettingsFor, ExperimentalFeatureSettings)
		),
		current_user_version: IDL.Opt(IDL.Nat64)
	});
	const SaveNetworksSettingsRequest = IDL.Record({
		networks: IDL.Vec(IDL.Tuple(NetworkSettingsFor, NetworkSettings)),
		current_user_version: IDL.Opt(IDL.Nat64)
	});
	const UpdateTransactionFilterSettingsRequest = IDL.Record({
		filter: TransactionFilterSettings,
		current_user_version: IDL.Opt(IDL.Nat64)
	});

	return IDL.Service({
		add_user_dismissed_notification: IDL.Func(
			[AddDismissedNotificationRequest],
			[AddUserDismissedNotificationResult],
			[]
		),
		add_user_hidden_dapp_id: IDL.Func([AddHiddenDappIdRequest], [AddUserHiddenDappIdResult], []),
		allow_signing: IDL.Func([IDL.Opt(AllowSigningRequest)], [AllowSigningResult], []),
		btc_add_pending_transaction: IDL.Func(
			[BtcAddPendingTransactionRequest],
			[BtcAddPendingTransactionResult],
			[]
		),
		btc_get_current_fee_percentiles: IDL.Func(
			[BtcGetFeePercentilesRequest],
			[BtcGetFeePercentilesResult],
			['query']
		),
		btc_get_pending_transactions: IDL.Func(
			[BtcGetPendingTransactionsRequest],
			[BtcGetPendingTransactionsResult],
			[]
		),
		config: IDL.Func([], [Config], ['query']),
		create_active_user_transaction: IDL.Func(
			[CreateActiveUserTransactionRequest],
			[ActiveUserTransactionResult],
			[]
		),
		create_contact: IDL.Func([CreateContactRequest], [CreateContactResult], []),
		create_user_profile: IDL.Func([], [CreateUserProfileResult], []),
		delete_active_user_transaction: IDL.Func([IDL.Text], [DeleteActiveUserTransactionResult], []),
		delete_contact: IDL.Func([IDL.Nat64], [DeleteContactResult], []),
		exchange_rate_enabled: IDL.Func([], [IDL.Bool], ['query']),
		get_account_creation_timestamps: IDL.Func(
			[],
			[IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat64))],
			['query']
		),
		get_active_user_transactions: IDL.Func([], [GetActiveUserTransactionsResult], ['query']),
		get_allowed_cycles: IDL.Func([], [GetAllowedCyclesResult], []),
		get_api_keys: IDL.Func([], [ApiKeys], ['query']),
		get_canister_status: IDL.Func([], [CanisterStatusResultV2], []),
		get_contact: IDL.Func([IDL.Nat64], [GetContactResult], ['query']),
		get_contacts: IDL.Func([], [GetContactsResult], ['query']),
		get_exchange_rate: IDL.Func([TokenId], [IDL.Opt(ExchangeRate)], ['query']),
		get_exchange_rates: IDL.Func([], [IDL.Vec(IDL.Tuple(TokenId, IDL.Opt(ExchangeRate)))], []),
		get_user_agreement_history: IDL.Func([], [GetAgreementHistoryResult], ['query']),
		get_user_profile: IDL.Func([], [GetUserProfileResult], ['query']),
		get_user_transactions: IDL.Func(
			[GetUserTransactionsRequest],
			[GetUserTransactionsResult],
			['query']
		),
		has_user_profile: IDL.Func([], [HasUserProfileResponse], ['query']),
		http_request: IDL.Func([HttpRequest], [HttpResponse], ['query']),
		http_request_transform: IDL.Func([TransformArgs], [HttpRequestResult], ['query']),
		list_custom_tokens: IDL.Func([], [IDL.Vec(CustomToken)], []),
		new_user_signups_allowed: IDL.Func([], [IDL.Bool], ['query']),
		remove_custom_token: IDL.Func([CustomToken], [], []),
		save_user_transactions: IDL.Func(
			[SaveUserTransactionsRequest],
			[SaveUserTransactionsResult],
			[]
		),
		set_api_keys: IDL.Func([ApiKeys], [], []),
		set_custom_token: IDL.Func([CustomToken], [], []),
		set_exchange_rate_enabled: IDL.Func([IDL.Bool], [], []),
		set_exchange_rate_replicated: IDL.Func([IDL.Bool], [], []),
		set_many_custom_tokens: IDL.Func([IDL.Vec(CustomToken)], [], []),
		set_new_user_signups_allowed: IDL.Func([IDL.Bool], [], []),
		set_onramper_signing_secret: IDL.Func([IDL.Opt(IDL.Text)], [], []),
		set_user_show_testnets: IDL.Func([SetShowTestnetsRequest], [SetUserShowTestnetsResult], []),
		sign_onramper_widget_url: IDL.Func(
			[SignOnramperWidgetUrlRequest],
			[SignOnramperWidgetUrlResult],
			[]
		),
		stats: IDL.Func([], [Stats], ['query']),
		top_up_cycles_ledger: IDL.Func(
			[IDL.Opt(TopUpCyclesLedgerRequest)],
			[TopUpCyclesLedgerResult],
			[]
		),
		update_active_user_transaction: IDL.Func(
			[UpdateActiveUserTransactionRequest],
			[ActiveUserTransactionResult],
			[]
		),
		update_contact: IDL.Func([Contact], [GetContactResult], []),
		update_provider_agreements: IDL.Func(
			[UpdateProviderAgreementsRequest],
			[SetUserShowTestnetsResult],
			[]
		),
		update_user_agreements: IDL.Func(
			[UpdateUserAgreementsRequest],
			[SetUserShowTestnetsResult],
			[]
		),
		update_user_experimental_feature_settings: IDL.Func(
			[UpdateExperimentalFeaturesSettingsRequest],
			[SetUserShowTestnetsResult],
			[]
		),
		update_user_network_settings: IDL.Func(
			[SaveNetworksSettingsRequest],
			[SetUserShowTestnetsResult],
			[]
		),
		update_user_transaction_filter_settings: IDL.Func(
			[UpdateTransactionFilterSettingsRequest],
			[SetUserShowTestnetsResult],
			[]
		)
	});
};

export const init = ({ IDL }) => {
	const InitArg = IDL.Record({
		derivation_origin: IDL.Opt(IDL.Text),
		ii_canister_id: IDL.Opt(IDL.Principal),
		ecdsa_key_name: IDL.Text,
		cfs_canister_id: IDL.Opt(IDL.Principal),
		allowed_callers: IDL.Vec(IDL.Principal),
		ic_root_key_der: IDL.Opt(IDL.Vec(IDL.Nat8)),
		new_user_signups_allowed: IDL.Opt(IDL.Bool)
	});
	const Arg = IDL.Variant({ Upgrade: IDL.Null, Init: InitArg });

	return [Arg];
};
