#!/usr/bin/env bash

source /home/apprunner/.bashrc

# https://docs.docker.com/config/containers/multi-service_container/
# turn on bash's job control
set -m

dfx start --quiet &

./docker/wait-port "$DFX_PORT"

REPLICA_PORT="$(dfx info replica-port)"
./docker/wait-port "$REPLICA_PORT"

# In case we ever want to re-deploy or configure anything when the image is running. This can be implemented here.

# now we bring the primary process back into the foreground
# and leave it there
fg %1
