/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BtcNetwork = { Mainnet: null } | { Testnet: null };
export type CallType = { Send: null } | { Sign: null };
export interface Icrc21ConsentInfo {
	metadata: Icrc21ConsentMessageMetadata;
	consent_message: Icrc21ConsentMessage;
}
export type Icrc21ConsentMessage =
	| {
			FieldsDisplayMessage: {
				fields: Array<[string, Value]>;
				intent: string;
			};
	  }
	| { GenericDisplayMessage: string };
export interface Icrc21ConsentMessageMetadata {
	utc_offset_minutes: [] | [number];
	language: string;
}
export interface Icrc21ConsentMessageRequest {
	arg: Uint8Array;
	method: string;
	user_preferences: Icrc21ConsentMessageSpec;
}
export interface Icrc21ConsentMessageSpec {
	metadata: Icrc21ConsentMessageMetadata;
	device_spec: [] | [Icrc21DeviceSpec];
}
export type Icrc21DeviceSpec = { GenericDisplay: null } | { FieldsDisplay: null };
export interface Icrc21ErrorInfo {
	description: string;
}
export interface Outpoint {
	txid: Uint8Array;
	vout: number;
}
export type Result = { Ok: string } | { Err: string };
export type Result_1 = { Ok: Icrc21ConsentInfo } | { Err: Icrc21ErrorInfo };
export type Result_2 = { Ok: SchnorrPublicKeyResponse } | { Err: string };
export type Result_3 = { Ok: Uint8Array } | { Err: string };
export type Result_4 = { Ok: bigint } | { Err: string };
export type SchnorrAlgorithm = { ed25519: null } | { bip340secp256k1: null };
export interface SchnorrPublicKeyResponse {
	public_key: Uint8Array;
	chain_code: Uint8Array;
}
export interface Utxo {
	height: number;
	value: bigint;
	outpoint: Outpoint;
}
export type Value =
	| { Text: { content: string } }
	| {
			TokenAmount: {
				decimals: number;
				amount: bigint;
				symbol: string;
			};
	  }
	| { TimestampSeconds: { amount: bigint } }
	| { DurationSeconds: { amount: bigint } };
export interface _SERVICE {
	approve_erc20: ActorMethod<
		[CallType, bigint, bigint, bigint, bigint, bigint, bigint, string],
		Result
	>;
	btc_p2tr_raw_key_address: ActorMethod<[Principal, BtcNetwork], Result>;
	custom_approve_erc20: ActorMethod<
		[CallType, bigint, bigint, bigint, bigint, bigint, bigint, string, string],
		Result
	>;
	custom_deposit_erc20: ActorMethod<
		[CallType, bigint, bigint, bigint, bigint, bigint, bigint, string],
		Result
	>;
	deposit_erc20: ActorMethod<
		[CallType, bigint, bigint, bigint, bigint, bigint, bigint, string],
		Result
	>;
	doge_address: ActorMethod<[[] | [Principal], boolean], string>;
	eth_address: ActorMethod<[[] | [Principal]], string>;
	eth_call_contract: ActorMethod<
		[CallType, bigint, bigint, bigint, bigint, bigint, bigint, string, string],
		Result
	>;
	icrc21_canister_call_consent_message: ActorMethod<[Icrc21ConsentMessageRequest], Result_1>;
	mint_cketh: ActorMethod<[CallType, bigint, bigint, bigint, bigint, bigint, bigint], Result>;
	personal_sign: ActorMethod<[string], Result>;
	public_key: ActorMethod<[SchnorrAlgorithm], Result_2>;
	send_btc: ActorMethod<[CallType, string, bigint, bigint, BtcNetwork, Array<Utxo>], Result>;
	send_erc20: ActorMethod<
		[CallType, bigint, bigint, bigint, bigint, bigint, bigint, string, string],
		Result
	>;
	send_eth: ActorMethod<[CallType, string, bigint, bigint, bigint, bigint, bigint, bigint], Result>;
	send_ordinal: ActorMethod<[CallType, string, bigint, BtcNetwork, Utxo, Utxo], Result>;
	sign_doge: ActorMethod<[string, bigint, bigint, Array<Utxo>, boolean], Result>;
	sign_hash: ActorMethod<[Uint8Array], Result>;
	sign_sol: ActorMethod<[Uint8Array], Result_3>;
	solana_address: ActorMethod<[Principal], Result>;
	ton_address: ActorMethod<[Principal], Result>;
	transaction_count: ActorMethod<[[] | [Principal], bigint], Result_4>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
