/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const CallType = IDL.Variant({ Send: IDL.Null, Sign: IDL.Null });
	const Result = IDL.Variant({ Ok: IDL.Text, Err: IDL.Text });
	const BtcNetwork = IDL.Variant({
		Mainnet: IDL.Null,
		Testnet: IDL.Null
	});
	const Icrc21ConsentMessageMetadata = IDL.Record({
		utc_offset_minutes: IDL.Opt(IDL.Int16),
		language: IDL.Text
	});
	const Icrc21DeviceSpec = IDL.Variant({
		GenericDisplay: IDL.Null,
		FieldsDisplay: IDL.Null
	});
	const Icrc21ConsentMessageSpec = IDL.Record({
		metadata: Icrc21ConsentMessageMetadata,
		device_spec: IDL.Opt(Icrc21DeviceSpec)
	});
	const Icrc21ConsentMessageRequest = IDL.Record({
		arg: IDL.Vec(IDL.Nat8),
		method: IDL.Text,
		user_preferences: Icrc21ConsentMessageSpec
	});
	const Value = IDL.Variant({
		Text: IDL.Record({ content: IDL.Text }),
		TokenAmount: IDL.Record({
			decimals: IDL.Nat8,
			amount: IDL.Nat64,
			symbol: IDL.Text
		}),
		TimestampSeconds: IDL.Record({ amount: IDL.Nat64 }),
		DurationSeconds: IDL.Record({ amount: IDL.Nat64 })
	});
	const Icrc21ConsentMessage = IDL.Variant({
		FieldsDisplayMessage: IDL.Record({
			fields: IDL.Vec(IDL.Tuple(IDL.Text, Value)),
			intent: IDL.Text
		}),
		GenericDisplayMessage: IDL.Text
	});
	const Icrc21ConsentInfo = IDL.Record({
		metadata: Icrc21ConsentMessageMetadata,
		consent_message: Icrc21ConsentMessage
	});
	const Icrc21ErrorInfo = IDL.Record({ description: IDL.Text });
	const Result_1 = IDL.Variant({
		Ok: Icrc21ConsentInfo,
		Err: Icrc21ErrorInfo
	});
	const SchnorrAlgorithm = IDL.Variant({
		ed25519: IDL.Null,
		bip340secp256k1: IDL.Null
	});
	const SchnorrPublicKeyResponse = IDL.Record({
		public_key: IDL.Vec(IDL.Nat8),
		chain_code: IDL.Vec(IDL.Nat8)
	});
	const Result_2 = IDL.Variant({
		Ok: SchnorrPublicKeyResponse,
		Err: IDL.Text
	});
	const Outpoint = IDL.Record({
		txid: IDL.Vec(IDL.Nat8),
		vout: IDL.Nat32
	});
	const Utxo = IDL.Record({
		height: IDL.Nat32,
		value: IDL.Nat64,
		outpoint: Outpoint
	});
	const Result_3 = IDL.Variant({ Ok: IDL.Vec(IDL.Nat8), Err: IDL.Text });
	const Result_4 = IDL.Variant({ Ok: IDL.Nat, Err: IDL.Text });

	return IDL.Service({
		approve_erc20: IDL.Func(
			[CallType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64, IDL.Text],
			[Result],
			[]
		),
		btc_p2tr_raw_key_address: IDL.Func([IDL.Principal, BtcNetwork], [Result], []),
		custom_approve_erc20: IDL.Func(
			[CallType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64, IDL.Text, IDL.Text],
			[Result],
			[]
		),
		custom_deposit_erc20: IDL.Func(
			[CallType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64, IDL.Text],
			[Result],
			[]
		),
		deposit_erc20: IDL.Func(
			[CallType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64, IDL.Text],
			[Result],
			[]
		),
		doge_address: IDL.Func([IDL.Opt(IDL.Principal), IDL.Bool], [IDL.Text], []),
		eth_address: IDL.Func([IDL.Opt(IDL.Principal)], [IDL.Text], []),
		eth_call_contract: IDL.Func(
			[CallType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64, IDL.Text, IDL.Text],
			[Result],
			[]
		),
		icrc21_canister_call_consent_message: IDL.Func([Icrc21ConsentMessageRequest], [Result_1], []),
		mint_cketh: IDL.Func(
			[CallType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64],
			[Result],
			[]
		),
		personal_sign: IDL.Func([IDL.Text], [Result], []),
		public_key: IDL.Func([SchnorrAlgorithm], [Result_2], []),
		send_btc: IDL.Func(
			[CallType, IDL.Text, IDL.Nat64, IDL.Nat64, BtcNetwork, IDL.Vec(Utxo)],
			[Result],
			[]
		),
		send_erc20: IDL.Func(
			[CallType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64, IDL.Text, IDL.Text],
			[Result],
			[]
		),
		send_eth: IDL.Func(
			[CallType, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat64],
			[Result],
			[]
		),
		send_ordinal: IDL.Func([CallType, IDL.Text, IDL.Nat64, BtcNetwork, Utxo, Utxo], [Result], []),
		sign_doge: IDL.Func([IDL.Text, IDL.Nat64, IDL.Nat64, IDL.Vec(Utxo), IDL.Bool], [Result], []),
		sign_hash: IDL.Func([IDL.Vec(IDL.Nat8)], [Result], []),
		sign_sol: IDL.Func([IDL.Vec(IDL.Nat8)], [Result_3], []),
		solana_address: IDL.Func([IDL.Principal], [Result], []),
		ton_address: IDL.Func([IDL.Principal], [Result], []),
		transaction_count: IDL.Func([IDL.Opt(IDL.Principal), IDL.Nat64], [Result_4], [])
	});
};

export const init = ({ IDL }) => {
	return [];
};
