/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const GetBlocksResult = IDL.Rec();
	const Value = IDL.Rec();
	const GetArchivesArgs = IDL.Record({ from: IDL.Opt(IDL.Principal) });
	const GetArchivesResult = IDL.Vec(
		IDL.Record({
			end: IDL.Nat,
			canister_id: IDL.Principal,
			start: IDL.Nat
		})
	);
	const GetBlocksArgs = IDL.Vec(IDL.Record({ start: IDL.Nat, length: IDL.Nat }));
	Value.fill(
		IDL.Variant({
			Int: IDL.Int,
			Map: IDL.Vec(IDL.Tuple(IDL.Text, Value)),
			Nat: IDL.Nat,
			Blob: IDL.Vec(IDL.Nat8),
			Text: IDL.Text,
			Array: IDL.Vec(Value)
		})
	);
	GetBlocksResult.fill(
		IDL.Record({
			log_length: IDL.Nat,
			blocks: IDL.Vec(IDL.Record({ id: IDL.Nat, block: Value })),
			archived_blocks: IDL.Vec(
				IDL.Record({
					args: GetBlocksArgs,
					callback: IDL.Func([GetBlocksArgs], [GetBlocksResult], ['query'])
				})
			)
		})
	);
	const DataCertificate = IDL.Record({
		certificate: IDL.Vec(IDL.Nat8),
		hash_tree: IDL.Vec(IDL.Nat8)
	});

	return IDL.Service({
		icrc3_get_archives: IDL.Func([GetArchivesArgs], [GetArchivesResult], ['query']),
		icrc3_get_blocks: IDL.Func([GetBlocksArgs], [GetBlocksResult], ['query']),
		icrc3_get_tip_certificate: IDL.Func([], [IDL.Opt(DataCertificate)], ['query']),
		icrc3_supported_block_types: IDL.Func(
			[],
			[IDL.Vec(IDL.Record({ url: IDL.Text, block_type: IDL.Text }))],
			['query']
		)
	});
};

export const init = ({ IDL }) => {
	return [];
};
