/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DataCertificate {
	/**
	 * See https://internetcomputer.org/docs/current/references/ic-interface-spec#certification
	 */
	certificate: Uint8Array;
	/**
	 * CBOR encoded hash_tree
	 */
	hash_tree: Uint8Array;
}
export interface GetArchivesArgs {
	/**
	 * The last archive seen by the client.
	 * The Ledger will return archives coming
	 * after this one if set, otherwise it
	 * will return the first archives.
	 */
	from: [] | [Principal];
}
export type GetArchivesResult = Array<{
	/**
	 * The last block in the archive
	 */
	end: bigint;
	/**
	 * The id of the archive
	 */
	canister_id: Principal;
	/**
	 * The first block in the archive
	 */
	start: bigint;
}>;
export type GetBlocksArgs = Array<{ start: bigint; length: bigint }>;
export interface GetBlocksResult {
	/**
	 * Total number of blocks in the
	 * block log
	 */
	log_length: bigint;
	blocks: Array<{ id: bigint; block: Value }>;
	archived_blocks: Array<{ args: GetBlocksArgs; callback: [Principal, string] }>;
}
export type Value =
	| { Int: bigint }
	| { Map: Array<[string, Value]> }
	| { Nat: bigint }
	| { Blob: Uint8Array }
	| { Text: string }
	| { Array: Array<Value> };
export interface _SERVICE {
	icrc3_get_archives: ActorMethod<[GetArchivesArgs], GetArchivesResult>;
	icrc3_get_blocks: ActorMethod<[GetBlocksArgs], GetBlocksResult>;
	icrc3_get_tip_certificate: ActorMethod<[], [] | [DataCertificate]>;
	icrc3_supported_block_types: ActorMethod<[], Array<{ url: string; block_type: string }>>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
