const EXPLORER_URLS = {
	ETHEREUM: 'https://etherscan.io',
	SEPOLIA: 'https://sepolia.etherscan.io',
	ICP: 'https://dashboard.internetcomputer.org',
	CKETH: 'https://dashboard.internetcomputer.org/ethereum',
	CKETH_SEPOLIA: 'https://dashboard.internetcomputer.org/sepoliaeth',
	CKBTC: 'https://dashboard.internetcomputer.org/bitcoin',
	CKBTC_TESTNET: 'https://dashboard.internetcomputer.org/testbtc',
	SNS: 'https://dashboard.internetcomputer.org/sns',
	BTC_MAINNET: 'https://blockstream.info',
	BTC_TESTNET: 'https://blockstream.info/testnet',
	BTC_REGTEST: 'https://blockstream.regtest.trustless.computer/regtest',
	SOL_MAINNET: 'https://solscan.io/$args',
	SOL_DEVNET: 'https://solscan.io/$args?cluster=devnet',
	BASE: 'https://basescan.org',
	BASE_SEPOLIA: 'https://sepolia.basescan.org',
	BSC: 'https://bscscan.com',
	BSC_TESTNET: 'https://testnet.bscscan.com',
	POLYGON: 'https://polygonscan.com',
	POLYGON_AMOY: 'https://amoy.polygonscan.com/',
	ARBITRUM: 'https://arbiscan.io',
	ARBITRUM_SEPOLIA: 'https://sepolia.arbiscan.io'
};

export const {
	ETHEREUM: ETHEREUM_EXPLORER_URL,
	SEPOLIA: SEPOLIA_EXPLORER_URL,
	ICP: ICP_EXPLORER_URL,
	CKETH: CKETH_EXPLORER_URL,
	CKETH_SEPOLIA: CKETH_SEPOLIA_EXPLORER_URL,
	CKBTC: CKBTC_EXPLORER_URL,
	CKBTC_TESTNET: CKBTC_TESTNET_EXPLORER_URL,
	SNS: SNS_EXPLORER_URL,
	BTC_MAINNET: BTC_MAINNET_EXPLORER_URL,
	BTC_TESTNET: BTC_TESTNET_EXPLORER_URL,
	BTC_REGTEST: BTC_REGTEST_EXPLORER_URL,
	SOL_MAINNET: SOL_MAINNET_EXPLORER_URL,
	SOL_DEVNET: SOL_DEVNET_EXPLORER_URL,
	BASE: BASE_EXPLORER_URL,
	BASE_SEPOLIA: BASE_SEPOLIA_EXPLORER_URL,
	BSC: BSC_EXPLORER_URL,
	BSC_TESTNET: BSC_TESTNET_EXPLORER_URL,
	POLYGON: POLYGON_EXPLORER_URL,
	POLYGON_AMOY: POLYGON_AMOY_EXPLORER_URL,
	ARBITRUM: ARBITRUM_EXPLORER_URL,
	ARBITRUM_SEPOLIA: ARBITRUM_SEPOLIA_EXPLORER_URL
} = EXPLORER_URLS;
