//! Selected backend canister API signatures.
#![allow(clippy::missing_errors_doc)] // The code is auto-generated.  Maybe `didc bind` will preserve comments in future.
use candid::{self, Principal};
use ic_cdk::call::{Call, CallResult as Result};

use crate::types::Stats;

/// Client for the backend canister, implementing a subset of the API.
///
/// Note: The canister signatures are generated by: `didc bind --type rs src/backend/backend.did`
///       It _may_ make sense to generate the entire API and types in this way.  That would
/// guarantee       that the types are in sync with the candid file.  However at the time of writing
/// there is       not a nice way of adding derivations to types generated in this way. It would
/// make sense       to wait for a nice solution to that first.  If automatic derivation is
/// absolutely       required, there are hacky bash scripts to add derivations to the generated rust
/// in the       nns-dapp repository.
pub struct Service(pub Principal);
impl Service {
    pub async fn stats(&self) -> Result<(Stats,)> {
        Call::unbounded_wait(self.0, "stats")
            .with_arg(())
            .await?
            .candid()
            .map_err(ic_cdk::call::Error::from)
    }
}
