/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

/**
 * Error returned when placing a limit order fails. See the disposition
 * contract at the top of this file.
 */
export interface AddLimitOrderError {
	kind:
		| {
				TemporaryError:
					| []
					| [
							{
								/**
								 * Trading is halted (globally or on this pair); no new orders are accepted.
								 */
								TradingHalted: null;
							}
					  ];
		  }
		| {
				RequestError:
					| []
					| [
							| {
									/**
									 * The amount exceeds the maximum supported value.
									 */
									AmountExceedsMaximum: null;
							  }
							| {
									/**
									 * The price is not a positive multiple of the tick size.
									 */
									InvalidPrice: { price: bigint; tick_size: bigint };
							  }
							| {
									/**
									 * The quantity is not a positive multiple of the lot size.
									 */
									InvalidQuantity: { lot_size: bigint; quantity: bigint };
							  }
							| {
									/**
									 * The caller's free balance in `token` is below `required`.
									 * For a `Sell`, `token` is the base and `required` is `quantity`.
									 * For a `Buy`, `token` is the quote and `required` is the scaled
									 * quote amount `price × quantity / 10^base_decimals`.
									 */
									InsufficientBalance: {
										token: TokenId;
										available: bigint;
										required: bigint;
									};
							  }
							| {
									/**
									 * The order's notional (price × quantity / 10^base_decimals, in
									 * quote smallest units) is below `min` or above `max`.
									 */
									InvalidNotional: {
										max: [] | [bigint];
										min: bigint;
										notional: bigint;
									};
							  }
							| {
									/**
									 * The requested trading pair is not registered.
									 */
									UnknownTradingPair: null;
							  }
					  ];
		  }
		| { InternalError: [] | [never] };
	message: [] | [string];
}
/**
 * Event payload for adding a limit order.
 */
export interface AddLimitOrderEvent {
	side: Side;
	user: Principal;
	quantity: bigint;
	order_id: EventOrderId;
	price: bigint;
	time_in_force: TimeInForce;
}
/**
 * Error returned by the add_trading_pair endpoint.
 */
export type AddTradingPairError =
	| {
			/**
			 * The tick size must be greater than zero.
			 */
			InvalidTickSize: null;
	  }
	| {
			/**
			 * The caller is not a controller of the canister.
			 */
			NotController: null;
	  }
	| {
			/**
			 * A trading pair with the same base and quote tokens already exists.
			 */
			TradingPairAlreadyExists: null;
	  }
	| {
			/**
			 * The lot size must be greater than zero.
			 */
			InvalidLotSize: null;
	  }
	| {
			/**
			 * The notional bounds are invalid: min_notional is zero, a bound is too
			 * large to fit the 256-bit quantity representation, or max_notional is set
			 * and smaller than min_notional.
			 */
			InvalidNotional: {
				min_notional: bigint;
				max_notional: [] | [bigint];
			};
	  }
	| {
			/**
			 * The submitted token metadata does not match the previously registered metadata.
			 */
			InconsistentTokenMetadata: {
				token: TokenId;
				submitted: TokenMetadata;
				expected: TokenMetadata;
			};
	  }
	| {
			/**
			 * The base and quote tokens are the same.
			 */
			BaseEqualsQuote: null;
	  }
	| {
			/**
			 * One of the fee rates is outside 0..=10_000 bps; the carried value is the offending bps.
			 */
			InvalidBasisPoint: number;
	  }
	| {
			/**
			 * The base token has too many decimals for settlement to be representable
			 * (10^base_decimals must fit a nat64, i.e. decimals <= 19).
			 */
			BaseDecimalsTooLarge: { decimals: number };
	  }
	| {
			/**
			 * tick_size * lot_size is not a multiple of 10^base_decimals, so some fills
			 * could not settle to an exact quote amount. Choose a coarser tick or lot.
			 */
			IndivisibleTickLotForBaseDecimals: {
				lot_size: bigint;
				base_decimals: number;
				tick_size: bigint;
			};
	  };
/**
 * Event payload for adding a trading pair.
 */
export interface AddTradingPairEvent {
	quote_metadata: TokenMetadata;
	base: TokenId;
	quote: TokenId;
	min_notional: bigint;
	book_id: bigint;
	lot_size: bigint;
	taker_fee_bps: number;
	maker_fee_bps: number;
	base_metadata: TokenMetadata;
	tick_size: bigint;
	max_notional: [] | [bigint];
}
/**
 * Request to add a new trading pair to the canister.
 */
export interface AddTradingPairRequest {
	/**
	 * The base token of the pair.
	 */
	base: Token;
	/**
	 * The quote token of the pair.
	 */
	quote: Token;
	/**
	 * Minimum order notional in quote token smallest units. Must be greater than zero.
	 */
	min_notional: bigint;
	/**
	 * Minimum order quantity, in base-token smallest units (same scale as
	 * `quantity`). Must be greater than zero.
	 */
	lot_size: bigint;
	/**
	 * Taker fee rate in basis points (1 bps = 0.01 %). Must be in 0..=10_000.
	 */
	taker_fee_bps: number;
	/**
	 * Maker fee rate in basis points (1 bps = 0.01 %). Must be in 0..=10_000.
	 */
	maker_fee_bps: number;
	/**
	 * Minimum price increment, in quote-token smallest units per one whole
	 * base token (same scale as `price`; see top-of-file unit conventions).
	 * Must be greater than zero. Additionally, `tick_size × lot_size` must
	 * be a multiple of `10^base_decimals` so every fill settles to an exact
	 * integer quote amount.
	 */
	tick_size: bigint;
	/**
	 * Maximum order notional in quote token smallest units, if any. When set,
	 * must be greater than or equal to min_notional.
	 */
	max_notional: [] | [bigint];
}
export type AddTradingPairResult = { Ok: null } | { Err: AddTradingPairError };
/**
 * A user's balance for a given token.
 */
export interface Balance {
	/**
	 * Funds available for new orders or withdrawal.
	 */
	free: bigint;
	/**
	 * Funds locked by open orders.
	 */
	reserved: bigint;
}
/**
 * Balance movement recorded during settlement. `from_order` / `to_order` /
 * `order` are order sequence numbers (`OrderSeq`) that the canister resolves
 * to principals via its order history at apply time — they are not user
 * principals.
 */
export type BalanceOperation =
	| {
			Transfer: {
				/**
				 * Fee withheld from the credited transfer for the per-token fee
				 * pool.
				 */
				fee: [] | [bigint];
				token: PairToken;
				to_order: bigint;
				from_order: bigint;
				amount: bigint;
			};
	  }
	| {
			Unreserve: { token: PairToken; order: bigint; amount: bigint };
	  };
/**
 * Error returned when canceling a limit order fails. See the disposition
 * contract at the top of this file.
 */
export interface CancelLimitOrderError {
	kind:
		| { TemporaryError: [] | [never] }
		| {
				RequestError:
					| []
					| [
							| {
									/**
									 * No order with the given ID exists.
									 */
									OrderNotFound: null;
							  }
							| {
									/**
									 * The caller does not own the order.
									 */
									NotOrderOwner: null;
							  }
							| {
									/**
									 * The order has reached a terminal state (Filled, Canceled, or
									 * Expired) and can no longer be canceled.
									 */
									OrderAlreadyTerminal: null;
							  }
							| {
									/**
									 * The supplied order id was not a well-formed order id.
									 */
									InvalidOrderId: null;
							  }
					  ];
		  }
		| { InternalError: [] | [never] };
	message: [] | [string];
}
/**
 * / Event payload for canceling a limit order.
 */
export interface CancelLimitOrderEvent {
	order_id: EventOrderId;
}
/**
 * Error returned by the deposit endpoint. See the disposition contract at the
 * top of this file.
 */
export interface DepositError {
	kind:
		| {
				TemporaryError:
					| []
					| [
							| {
									/**
									 * The inter-canister call to the token ledger failed.
									 */
									CallFailed: {
										method: string;
										ledger: Principal;
										reason: string;
									};
							  }
							| {
									/**
									 * The token ledger is temporarily unavailable.
									 */
									LedgerTemporarilyUnavailable: null;
							  }
							| {
									/**
									 * Another deposit or withdrawal is already in flight for this
									 * (caller, token). Retry once the previous operation completes.
									 */
									OperationInProgress: null;
							  }
					  ];
		  }
		| {
				RequestError:
					| []
					| [
							| {
									/**
									 * The amount exceeds the maximum supported value.
									 */
									AmountExceedsMaximum: null;
							  }
							| {
									/**
									 * The caller's ICRC-2 allowance to the canister is not large enough.
									 */
									InsufficientAllowance: { allowance: bigint };
							  }
							| {
									/**
									 * The token is not part of any registered trading pair.
									 */
									UnsupportedToken: { token_id: TokenId };
							  }
							| {
									/**
									 * The caller's external wallet does not hold enough funds.
									 */
									InsufficientFunds: { balance: bigint };
							  }
					  ];
		  }
		| {
				InternalError:
					| []
					| [
							| {
									/**
									 * The ledger's response could not be Candid-decoded.
									 */
									CandidDecodeFailed: {
										method: string;
										ledger: Principal;
										reason: string;
									};
							  }
							| {
									/**
									 * The icrc2_transfer_from call returned an unexpected ledger error.
									 */
									LedgerError: { reason: string };
							  }
					  ];
		  };
	message: [] | [string];
}
/**
 * Event payload for a deposit.
 */
export interface DepositEvent {
	token: TokenId;
	user: Principal;
	amount: bigint;
}
/**
 * Request to deposit tokens into the canister.
 */
export interface DepositRequest {
	/**
	 * The token to deposit.
	 */
	token_id: TokenId;
	/**
	 * The amount to deposit, in the token's base units.
	 * The caller's ICRC-2 allowance to the canister on the token ledger must cover
	 * `amount + ledger_fee` (the `icrc2_transfer_from` fee is charged against
	 * the allowance on top of the transferred amount).
	 */
	amount: bigint;
}
/**
 * Response after a successful deposit.
 */
export interface DepositResponse {
	/**
	 * The block index of the transfer on the token ledger.
	 */
	block_index: bigint;
}
export type DepositResult = { Ok: DepositResponse } | { Err: DepositError };
/**
 * A canister event with a timestamp.
 */
export interface Event {
	timestamp: bigint;
	payload: EventType;
}
/**
 * Structured order identifier used in events.
 */
export interface EventOrderId {
	seq: bigint;
	book_id: bigint;
}
/**
 * Type of a canister event.
 */
export type EventType =
	| { Withdraw: WithdrawEvent }
	| { AddTradingPair: AddTradingPairEvent }
	| { Upgrade: UpgradeArg }
	| { Init: InitArg }
	| { Deposit: DepositEvent }
	| { Settling: SettlingEvent }
	| { Matching: MatchingEvent }
	| { CancelLimitOrder: CancelLimitOrderEvent }
	| { SetHalt: SetHaltEvent }
	| { AddLimitOrder: AddLimitOrderEvent };
/**
 * Selector for filtering tokens. New variants may be added in
 * backward-compatible upgrades.
 */
export type FilterToken = { ById: TokenId };
/**
 * Error reported by `get_balances` / `get_fee_balances`. These are read
 * endpoints, so a failure dooms the whole call (no per-entry partial success).
 * See the disposition contract at the top of this file.
 */
export interface GetBalancesError {
	kind:
		| { TemporaryError: [] | [never] }
		| {
				RequestError:
					| []
					| [
							| {
									/**
									 * The filter referenced a token that the canister does not support.
									 */
									TokenNotSupported: FilterToken;
							  }
							| {
									/**
									 * The filter exceeded the maximum number of entries.
									 */
									FilterTooLarge: { len: number; max: number };
							  }
					  ];
		  }
		| { InternalError: [] | [never] };
	message: [] | [string];
}
/**
 * Response shape for `get_balances`.
 */
export type GetBalancesResult = { Ok: Array<UserTokenBalance> } | { Err: GetBalancesError };
/**
 * Arguments for the get_events query.
 */
export interface GetEventsArgs {
	start: bigint;
	length: bigint;
}
/**
 * Result of the get_events query.
 */
export interface GetEventsResult {
	total_event_count: bigint;
	events: Array<Event>;
}
/**
 * / Request for `get_my_orders`.
 */
export interface GetMyOrdersArgs {
	/**
	 * / How to select the caller's orders.
	 */
	filter: GetMyOrdersFilter;
}
/**
 * Error returned by the `get_my_orders` query. See the disposition contract at
 * the top of this file.
 */
export interface GetMyOrdersError {
	kind:
		| { TemporaryError: [] | [never] }
		| {
				RequestError:
					| []
					| [
							| {
									/**
									 * A well-formed order id in the filter (`ById` target or
									 * `ByPage.after` cursor) is unknown or not owned by the caller.
									 */
									OrderNotFound: null;
							  }
							| {
									/**
									 * An order id in the filter (`ById` target or `ByPage.after`
									 * cursor) was not a well-formed order id.
									 */
									InvalidOrderId: null;
							  }
					  ];
		  }
		| { InternalError: [] | [never] };
	message: [] | [string];
}
/**
 * / Selector for `get_my_orders`: a point lookup by id or a page.
 */
export type GetMyOrdersFilter =
	| {
			/**
			 * / Return the single matching order if the caller owns it, else empty.
			 */
			ById: OrderId;
	  }
	| {
			/**
			 * / Return a page over the caller's orders, newest first. `length` is capped
			 * / at 100. Pages via a cursor: pass the previous page's last order id as
			 * / `after`; null starts from the newest order.
			 */
			ByPage: { after: [] | [OrderId]; length: number };
	  };
/**
 * Error returned by the `get_order_book_depth` query. See the disposition
 * contract at the top of this file.
 */
export interface GetOrderBookDepthError {
	kind:
		| { TemporaryError: [] | [never] }
		| {
				RequestError:
					| []
					| [
							| {
									/**
									 * The requested depth limit exceeds the maximum supported value (1000).
									 */
									LimitTooLarge: { max: number; requested: number };
							  }
							| {
									/**
									 * The requested trading pair is not registered.
									 */
									UnknownTradingPair: null;
							  }
					  ];
		  }
		| { InternalError: [] | [never] };
	message: [] | [string];
}
/**
 * Request for the `get_order_book_depth` query.
 */
export interface GetOrderBookDepthRequest {
	/**
	 * Maximum number of price levels returned per side. When absent, the canister
	 * returns 100 levels per side. The maximum accepted value is 1000; above
	 * that the query returns `LimitTooLarge`. `opt 0` is accepted and returns
	 * empty `bids`/`asks` vectors.
	 */
	limit: [] | [number];
	/**
	 * The trading pair whose depth should be returned.
	 */
	trading_pair: TradingPair;
}
export type GetOrderBookDepthResult = { Ok: OrderBookDepth } | { Err: GetOrderBookDepthError };
/**
 * Error returned by the `get_order_book_ticker` query. See the disposition
 * contract at the top of this file.
 */
export interface GetOrderBookTickerError {
	kind:
		| { TemporaryError: [] | [never] }
		| {
				RequestError:
					| []
					| [
							{
								/**
								 * The requested trading pair is not registered.
								 */
								UnknownTradingPair: null;
							}
					  ];
		  }
		| { InternalError: [] | [never] };
	message: [] | [string];
}
export type GetOrderBookTickerResult = { Ok: OrderBookTicker } | { Err: GetOrderBookTickerError };
/**
 * Argument for canister initialization.
 */
export interface InitArg {
	/**
	 * Maximum pending orders matched per chunked-execution chunk.
	 */
	max_orders_per_chunk: number;
	/**
	 * Controls who may call update endpoints.
	 */
	mode: Mode;
	/**
	 * Maximum instructions consumed before a chunk yields.
	 */
	instruction_budget: bigint;
}
export interface LimitOrderRequest {
	/**
	 * The trading pair to place the order on.
	 */
	pair: TradingPair;
	/**
	 * Whether this is a buy or sell order.
	 */
	side: Side;
	/**
	 * Order quantity in base-token smallest units. Must be a positive
	 * multiple of the pair's `lot_size`.
	 */
	quantity: bigint;
	/**
	 * Limit price in quote-token smallest units per one whole base token
	 * (see top-of-file unit conventions). Must be a positive multiple of
	 * the pair's `tick_size`.
	 */
	price: bigint;
	/**
	 * Time-in-force policy. Absent defaults to GoodTilCanceled.
	 */
	time_in_force: [] | [TimeInForce];
}
/**
 * Engine drove a matching round on `book_id`, processing these orders in
 * FIFO order. Drives replay of the matching engine.
 */
export interface MatchingEvent {
	orders: BigUint64Array;
	book_id: bigint;
}
/**
 * Controls who may call update endpoints on the canister.
 */
export type Mode =
	| {
			/**
			 * Only the listed principals may call update endpoints.
			 */
			RestrictedTo: Array<Principal>;
	  }
	| {
			/**
			 * Anyone may call update endpoints.
			 */
			GeneralAvailability: null;
	  };
/**
 * Argument passed to the canister on init or upgrade.
 */
export type OisyTradeArg = { Upgrade: [] | [UpgradeArg] } | { Init: InitArg };
/**
 * Price-aggregated depth view of an order book for a trading pair.
 */
export interface OrderBookDepth {
	/**
	 * Ask levels sorted by price ascending (best ask first).
	 */
	asks: Array<PriceLevel>;
	/**
	 * Bid levels sorted by price descending (best bid first).
	 */
	bids: Array<PriceLevel>;
}
/**
 * Top-of-book view of an order book for a trading pair.
 */
export interface OrderBookTicker {
	/**
	 * Best ask (lowest-priced sell level), or `null` if the ask side is empty.
	 */
	ask: [] | [PriceLevel];
	/**
	 * Best bid (highest-priced buy level), or `null` if the bid side is empty.
	 */
	bid: [] | [PriceLevel];
}
/**
 * Unique identifier for an order, assigned by the canister upon submission.
 * Opaque identifier, not meant to be interpreted by clients.
 * Encoded as a 32-character hex string.
 */
export type OrderId = string;
/**
 * / Full view of an order as stored by the canister.
 */
export interface OrderRecord {
	/**
	 * / Current lifecycle state.
	 */
	status: OrderStatus;
	/**
	 * / Principal that placed the order.
	 */
	owner: Principal;
	/**
	 * / Cumulative quantity filled so far, in base-token smallest units.
	 * / Remaining is `quantity − filled_quantity`.
	 */
	filled_quantity: bigint;
	/**
	 * / Whether the order is a buy or a sell.
	 */
	side: Side;
	/**
	 * / Submission time in nanoseconds since the Unix epoch.
	 */
	created_at: bigint;
	/**
	 * / Time of the most recent modifying event (fill, status transition, or
	 * / cancel) in nanoseconds since the Unix epoch; null until first modified.
	 */
	last_updated_at: [] | [bigint];
	/**
	 * / Quantity originally placed, in base-token smallest units.
	 */
	quantity: bigint;
	/**
	 * / Limit price as originally placed, in quote-token smallest units
	 * / per one whole base token (see top-of-file unit conventions).
	 */
	price: bigint;
	/**
	 * / Time-in-force policy the order was placed with.
	 */
	time_in_force: TimeInForce;
}
/**
 * Status of an order.
 */
export type OrderStatus =
	| {
			/**
			 * The order is open and resting in the order book.
			 */
			Open: null;
	  }
	| {
			/**
			 * The order has been fully filled.
			 */
			Filled: null;
	  }
	| {
			/**
			 * The order was terminated by the engine because its time-in-force could
			 * not be honored (a Fill-or-Kill that could not fully fill).
			 */
			Expired: null;
	  }
	| {
			/**
			 * / The order has been canceled.
			 */
			Canceled: null;
	  }
	| {
			/**
			 * The order is pending processing.
			 */
			Pending: null;
	  };
export type PairToken = { Base: null } | { Quote: null };
/**
 * A single price level in an order book, aggregated across all resting orders at that price.
 */
export interface PriceLevel {
	/**
	 * Total quantity, in base-token smallest units, across all resting
	 * orders at this price.
	 */
	quantity: bigint;
	/**
	 * Price in quote-token smallest units per one whole base token
	 * (see top-of-file unit conventions).
	 */
	price: bigint;
}
/**
 * Event payload recording a halt status change. `book_ids` is null for a
 * global change and a list of order book ids for a per-pair change. `halted`
 * is the new status applied to the targeted scope.
 */
export interface SetHaltEvent {
	book_ids: [] | [BigUint64Array];
	halted: boolean;
}
/**
 * Declarative record of the balance operations produced by a matching round
 * or a cancellation.
 */
export interface SettlingEvent {
	balance_operations: Array<BalanceOperation>;
	book_id: bigint;
}
/**
 * Side of an order.
 */
export type Side =
	| {
			/**
			 * Buy order (bid). On submission reserves `price × quantity / 10^base_decimals`
			 * of the *quote* token from the caller's free balance.
			 */
			Buy: null;
	  }
	| {
			/**
			 * Sell order (ask). On submission reserves `quantity` of the *base*
			 * token from the caller's free balance.
			 */
			Sell: null;
	  };
/**
 * Request to place a new limit order.
 * Time-in-force policy governing how long a limit order stays active in the
 * order book.
 */
export type TimeInForce =
	| {
			/**
			 * Must fill in full when the engine processes it, otherwise the whole order
			 * is killed with zero execution. Never rests.
			 */
			FillOrKill: null;
	  }
	| {
			/**
			 * Rests in the book until filled or canceled; may fill partially over time.
			 */
			GoodTilCanceled: null;
	  };
/**
 * A token with its identity and metadata.
 */
export interface Token {
	/**
	 * The token's unique identifier.
	 */
	id: TokenId;
	/**
	 * The token's metadata.
	 */
	metadata: TokenMetadata;
}
/**
 * A token identified by its ledger canister ID.
 */
export interface TokenId {
	/**
	 * The canister ID of the token's ledger.
	 */
	ledger_id: Principal;
}
/**
 * Metadata associated with a token.
 */
export interface TokenMetadata {
	/**
	 * The number of decimal places used by the token.
	 */
	decimals: number;
	/**
	 * The token's ticker symbol (e.g. "ckBTC").
	 */
	symbol: string;
}
/**
 * A trading pair identified by the base and quote token ledger principals.
 */
export interface TradingPair {
	/**
	 * The base token ledger canister principal.
	 */
	base: Principal;
	/**
	 * The quote token ledger canister principal.
	 */
	quote: Principal;
}
export interface TradingPairInfo {
	/**
	 * Whether trading on this pair is currently active or halted.
	 */
	status: TradingStatus;
	/**
	 * The base token.
	 */
	base: Token;
	/**
	 * The quote token.
	 */
	quote: Token;
	/**
	 * Minimum order notional in quote-token smallest units.
	 */
	min_notional: bigint;
	/**
	 * Minimum order quantity, in base-token smallest units. All order
	 * quantities must be a positive multiple of this value.
	 */
	lot_size: bigint;
	/**
	 * Taker fee rate, in basis points.
	 */
	taker_fee_bps: number;
	/**
	 * Maker fee rate, in basis points.
	 */
	maker_fee_bps: number;
	/**
	 * Minimum price increment, in the same units as `price` (quote-token
	 * smallest units per one whole base token). All order prices must be a
	 * positive multiple of this value.
	 */
	tick_size: bigint;
	/**
	 * Maximum order notional in quote-token smallest units, if any.
	 */
	max_notional: [] | [bigint];
}
/**
 * Information about a listed trading pair.
 * Whether trading on a pair is currently active or halted.
 */
export type TradingStatus =
	| {
			/**
			 * Trading on the pair is active.
			 */
			Trading: null;
	  }
	| {
			/**
			 * Trading on the pair is halted.
			 */
			Halted: null;
	  };
/**
 * Error returned by controller-gated endpoints when the caller is not
 * authorized to perform the requested action.
 */
export type UnauthorizedError = {
	/**
	 * The caller is not a controller of the canister.
	 */
	NotController: null;
};
export type UnauthorizedResult = { Ok: null } | { Err: UnauthorizedError };
/**
 * Argument for canister upgrade.
 */
export interface UpgradeArg {
	/**
	 * If set, overrides the current `max_orders_per_chunk`.
	 */
	max_orders_per_chunk: [] | [number];
	/**
	 * If set, changes who may call update endpoints.
	 */
	mode: [] | [Mode];
	/**
	 * If set, overrides the current `instruction_budget`.
	 */
	instruction_budget: [] | [bigint];
}
/**
 * / One entry in a `get_my_orders` response: an order the caller placed.
 */
export interface UserOrder {
	/**
	 * / The order's unique identifier.
	 */
	id: OrderId;
	/**
	 * / The full order record.
	 */
	order: OrderRecord;
	/**
	 * / The trading pair the order was placed on.
	 */
	pair: TradingPair;
}
/**
 * A single `(token, balance)` entry in a `get_balances` response.
 */
export interface UserTokenBalance {
	token: Token;
	balance: Balance;
}
/**
 * Error returned by the withdraw endpoint. See the disposition contract at the
 * top of this file.
 */
export interface WithdrawError {
	kind:
		| {
				TemporaryError:
					| []
					| [
							| {
									/**
									 * The inter-canister call to the token ledger failed.
									 */
									CallFailed: {
										method: string;
										ledger: Principal;
										reason: string;
									};
							  }
							| {
									/**
									 * The ledger fee changed between fetch and transfer; nothing
									 * happened on the ledger. Rare; retry.
									 */
									LedgerFeeChanged: null;
							  }
							| {
									/**
									 * The token ledger is temporarily unavailable.
									 */
									LedgerTemporarilyUnavailable: null;
							  }
							| {
									/**
									 * Another deposit or withdrawal is already in flight for this
									 * (caller, token). Retry once the previous operation completes.
									 */
									OperationInProgress: null;
							  }
					  ];
		  }
		| {
				RequestError:
					| []
					| [
							| {
									/**
									 * The amount exceeds the maximum supported value.
									 */
									AmountExceedsMaximum: null;
							  }
							| {
									/**
									 * The caller does not have enough free balance.
									 */
									InsufficientBalance: { available: bigint };
							  }
							| {
									/**
									 * The token is not part of any registered trading pair.
									 */
									UnsupportedToken: { token_id: TokenId };
							  }
							| {
									/**
									 * The requested amount is below the ledger's transfer fee.
									 * `min_amount` is the ledger's `icrc1_fee` + 1.
									 */
									AmountTooSmall: { min_amount: bigint };
							  }
					  ];
		  }
		| {
				InternalError:
					| []
					| [
							| {
									/**
									 * The ledger's response could not be Candid-decoded.
									 */
									CandidDecodeFailed: {
										method: string;
										ledger: Principal;
										reason: string;
									};
							  }
							| {
									/**
									 * The icrc1_transfer call returned an unexpected ledger error.
									 */
									LedgerError: { reason: string };
							  }
							| {
									/**
									 * The ledger reported insufficient funds against the canister's
									 * own accounting — a genuine invariant violation.
									 */
									LedgerInsufficientFunds: { balance: bigint };
							  }
					  ];
		  };
	message: [] | [string];
}
/**
 * Event payload for a successful withdrawal.
 */
export interface WithdrawEvent {
	token: TokenId;
	block_index: bigint;
	user: Principal;
	amount: bigint;
}
/**
 * Request to withdraw tokens from the canister.
 */
export interface WithdrawRequest {
	/**
	 * The token to withdraw.
	 */
	token_id: TokenId;
	/**
	 * The amount to withdraw from the caller's free balance, in the
	 * token's base units. The ledger transfer fee is deducted from this
	 * amount, so the caller receives `amount - ledger_fee` on the ledger;
	 * `amount` must therefore be strictly greater than `ledger_fee`
	 * (otherwise the call returns `Err(AmountTooSmall)`).
	 */
	amount: bigint;
}
/**
 * Response after a successful withdrawal.
 */
export interface WithdrawResponse {
	/**
	 * The block index of the transfer on the token ledger.
	 */
	block_index: bigint;
}
export type WithdrawResult = { Ok: WithdrawResponse } | { Err: WithdrawError };
export interface _SERVICE {
	/**
	 * Submit a new limit order. The order is queued for *asynchronous*
	 * processing by the matching engine; an `OrderId` is returned
	 * immediately. An `Ok` response means the order was accepted into the
	 * queue, not that it filled — call `get_my_orders` to observe the actual
	 * lifecycle (`Pending` → `Open` / `Filled` / `Canceled`).
	 */
	add_limit_order: ActorMethod<[LimitOrderRequest], { Ok: OrderId } | { Err: AddLimitOrderError }>;
	/**
	 * Add a new trading pair to the canister. Only callable by a controller.
	 */
	add_trading_pair: ActorMethod<[AddTradingPairRequest], AddTradingPairResult>;
	/**
	 * / Cancel a limit order previously submitted by the caller. Any remaining
	 * / reserved balance is credited back to the caller's free balance.
	 */
	cancel_limit_order: ActorMethod<[OrderId], { Ok: OrderRecord } | { Err: CancelLimitOrderError }>;
	/**
	 * Deposit tokens into the canister. Calls `icrc2_transfer_from` on the token
	 * ledger to pull `amount` from the caller to the canister, then
	 * credits the caller's free balance.
	 *
	 * The caller must have previously called `icrc2_approve` authorizing the canister
	 * as spender. The ledger charges its fee on both `icrc2_approve` and
	 * `icrc2_transfer_from`, so:
	 * - the allowance must cover `amount + ledger_fee`;
	 * - the caller's on-ledger balance must cover `amount + 2 × ledger_fee`.
	 */
	deposit: ActorMethod<[DepositRequest], DepositResult>;
	/**
	 * Query the caller's balances.
	 *
	 * - `null`: returns every token the caller holds with non-zero balance.
	 * - `opt vec { ... }`: looks up each entry in the filter (including
	 * zero balances). Duplicate filter entries are collapsed and returned
	 * only once. An empty filter (`opt vec {}`) returns an empty `Ok`
	 * vector, and is semantically distinct from `null`.
	 *
	 * The whole call fails with `TokenNotSupported` if the filter references
	 * a token the canister does not support — reads are cheap to re-issue, so
	 * there is no per-entry partial success.
	 *
	 * The order of entries in the returned `vec UserTokenBalance` is
	 * unspecified; callers must identify each result by the `token` field.
	 */
	get_balances: ActorMethod<[[] | [Array<FilterToken>]], GetBalancesResult>;
	/**
	 * *WARNING*: This is a debug endpoint, backwards-compatibility is not guaranteed.
	 * Returns events from the event log starting at the given index.
	 * The response contains at most 2000 events.
	 */
	get_events: ActorMethod<[GetEventsArgs], GetEventsResult>;
	/**
	 * Query the canister-owned fee pool. Mirrors `get_balances` shape:
	 *
	 * - `null`: returns every token with a non-zero fee balance.
	 * - `opt vec { ... }`: looks up each entry (including zero balances).
	 * Duplicates collapsed; empty filter returns an empty `Ok` vector.
	 *
	 * The whole call fails with `TokenNotSupported` if the filter references
	 * an unsupported token.
	 *
	 * Each returned `Balance` carries the fee amount in `free`;
	 * `reserved` is always zero (fees have no reserved concept).
	 */
	get_fee_balances: ActorMethod<[[] | [Array<FilterToken>]], GetBalancesResult>;
	/**
	 * Return the caller's orders, either a single order by id or a page,
	 * newest first. The argument is optional: an absent argument is equivalent
	 * to a page from the newest order with the maximum length.
	 * Returns `InvalidOrderId` if an order id (the `ById` target or the
	 * `ByPage` cursor) is malformed, and `OrderNotFound` if it is well-formed
	 * but unknown or not owned by the caller.
	 */
	get_my_orders: ActorMethod<
		[[] | [GetMyOrdersArgs]],
		{ Ok: Array<UserOrder> } | { Err: GetMyOrdersError }
	>;
	/**
	 * Query price-aggregated depth for a trading pair. See
	 * `GetOrderBookDepthRequest` for the semantics of the `limit` field.
	 * Returns `UnknownTradingPair` if the pair is not registered.
	 */
	get_order_book_depth: ActorMethod<[GetOrderBookDepthRequest], GetOrderBookDepthResult>;
	/**
	 * Query the top-of-book (best bid and best ask, each aggregated across all
	 * resting orders at that price) for a trading pair. Returns
	 * `UnknownTradingPair` if the pair is not registered. Either side of the
	 * returned `OrderBookTicker` may be `null` independently when that side of
	 * the book is empty.
	 */
	get_order_book_ticker: ActorMethod<[TradingPair], GetOrderBookTickerResult>;
	/**
	 * Query all listed trading pairs.
	 */
	get_trading_pairs: ActorMethod<[], Array<TradingPairInfo>>;
	/**
	 * Halt trading: a halted pair rejects new orders and is skipped by the
	 * matching engine, while cancels and withdrawals remain open. `null` halts
	 * the whole DEX; a list of pairs halts only those pairs. Only callable by a
	 * controller. Idempotent — halting already-halted scope succeeds. Traps if
	 * any listed pair is not registered, or if the list contains more than 100
	 * trading pairs.
	 */
	halt_trading: ActorMethod<[[] | [Array<TradingPair>]], UnauthorizedResult>;
	/**
	 * List every token registered with the canister. Intended as a primitive
	 * for clients that need to discover which tokens a user might hold
	 * (e.g. wallet-state recovery after losing local state).
	 */
	list_supported_tokens: ActorMethod<[], Array<Token>>;
	/**
	 * Resume trading. `null` clears the global halt and every per-pair halt; a
	 * list of pairs resumes only those pairs. Only callable by a controller.
	 * Idempotent — resuming an already-active scope succeeds. Traps if any
	 * listed pair is not registered, or if the list contains more than 100
	 * trading pairs.
	 */
	resume_trading: ActorMethod<[[] | [Array<TradingPair>]], UnauthorizedResult>;
	/**
	 * Withdraw tokens from the canister. Debits `amount` from the caller's
	 * free balance and transfers `amount - ledger_fee` to the caller via
	 * `icrc1_transfer` on the token ledger.
	 *
	 * `amount` must be strictly greater than the token ledger's fee
	 * (otherwise `AmountTooSmall`).
	 * Only free balance is eligible — funds reserved by open orders are not
	 * withdrawable until the order fills or is canceled.
	 */
	withdraw: ActorMethod<[WithdrawRequest], WithdrawResult>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
