// Placeholder — regenerated by CI via `npm run generate` from the candid pinned
// in dfx.json (dfinity/oisy-trade). Do not hand-edit; the real typings overwrite
// this file during the generate step.
import type { ActorMethod } from '@dfinity/agent';
import type { IDL } from '@dfinity/candid';

export interface _SERVICE {
	[key: string]: ActorMethod;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
