// Placeholder — regenerated by CI via `npm run generate` from the candid pinned
// in dfx.json (dfinity/oisy-trade). Do not hand-edit; the real factory overwrites
// this file during the generate step.
export const idlFactory = ({ IDL }) => IDL.Service({});
export const init = () => [];
