name: Release Notes

description: Publishes release notes

inputs:
  tag:
    description: Name of the tag
    required: true
  app-id:
    description: Please see actions/create-github-app-token@v1
    required: true
  private-key:
    description: Please see actions/create-github-app-token@v1
    required: true

runs:
  using: composite
  steps:
    - name: Create GitHub App Token
      uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - name: Publish Release Notes
      id: publish_release
      uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      with:
        version: ${{ inputs.tag }}
        tag: ${{ inputs.tag }}
        name: ${{ inputs.tag }}
        latest: true
        publish: true
