name: Release Notes

description: Publishes release notes

inputs:
  tag:
    description: Name of the tag
    required: true

runs:
  using: composite
  steps:
    - name: Create GitHub App Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.PR_AUTOMATION_BOT_PUBLIC_APP_ID }}
        private-key: ${{ secrets.PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY }}

    - name: Publish Release Notes
      id: publish_release
      uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      with:
        version: ${{ inputs.tag }}
        tag: ${{ inputs.tag }}
        name: ${{ inputs.tag }}
        latest: true
        publish: true
