<script lang="ts">
	import type { WizardStep } from '@dfinity/gix-components';
	import { isNullish, nonNullish } from '@dfinity/utils';
	import { getContext, onMount } from 'svelte';
	import BtcConvertForm from '$btc/components/convert/BtcConvertForm.svelte';
	import BtcConvertProgress from '$btc/components/convert/BtcConvertProgress.svelte';
	import BtcConvertReview from '$btc/components/convert/BtcConvertReview.svelte';
	import UtxosFeeContext from '$btc/components/fee/UtxosFeeContext.svelte';
	import { loadBtcPendingSentTransactions } from '$btc/services/btc-pending-sent-transactions.services';
	import { sendBtc } from '$btc/services/btc-send.services';
	import { UTXOS_FEE_CONTEXT_KEY } from '$btc/stores/utxos-fee.store';
	import { btcAddressStore } from '$icp/stores/btc.store';
	import ButtonBack from '$lib/components/ui/ButtonBack.svelte';
	import ButtonCancel from '$lib/components/ui/ButtonCancel.svelte';
	import {
		TRACK_COUNT_CONVERT_BTC_TO_CKBTC_ERROR,
		TRACK_COUNT_CONVERT_BTC_TO_CKBTC_SUCCESS
	} from '$lib/constants/analytics.contants';
	import {
		btcAddressMainnet,
		btcAddressRegtest,
		btcAddressTestnet
	} from '$lib/derived/address.derived';
	import { authIdentity } from '$lib/derived/auth.derived';
	import { ProgressStepsConvert } from '$lib/enums/progress-steps';
	import { WizardStepsConvert } from '$lib/enums/wizard-steps';
	import { trackEvent } from '$lib/services/analytics.services';
	import { nullishSignOut } from '$lib/services/auth.services';
	import { CONVERT_CONTEXT_KEY, type ConvertContext } from '$lib/stores/convert.store';
	import { i18n } from '$lib/stores/i18n.store';
	import { toastsError } from '$lib/stores/toasts.store';
	import type { OptionAmount } from '$lib/types/send';
	import { invalidAmount, isNullishOrEmpty } from '$lib/utils/input.utils';
	import {
		isNetworkIdBTCRegtest,
		isNetworkIdBTCTestnet,
		mapNetworkIdToBitcoinNetwork
	} from '$lib/utils/network.utils';

	interface Props {
		sendAmount: OptionAmount;
		receiveAmount?: number;
		convertProgressStep: string;
		currentStep?: WizardStep;
		formCancelAction?: 'back' | 'close';
		onBack: () => void;
		onClose: () => void;
		onNext: () => void;
	}

	let {
		sendAmount = $bindable(),
		receiveAmount = $bindable(),
		convertProgressStep = $bindable(),
		currentStep,
		formCancelAction = 'close',
		onBack,
		onClose,
		onNext
	}: Props = $props();

	const { store: utxosFeeStore } = getContext<UtxosFeeContext>(UTXOS_FEE_CONTEXT_KEY);

	const { sourceToken, destinationToken } = getContext<ConvertContext>(CONVERT_CONTEXT_KEY);

	const progress = (step: ProgressStepsConvert) => (convertProgressStep = step);

	let amountError = $state(false);

	let networkId = $derived($sourceToken.network.id);

	let sourceAddress = $derived(
		(isNetworkIdBTCTestnet(networkId)
			? $btcAddressTestnet
			: isNetworkIdBTCRegtest(networkId)
				? $btcAddressRegtest
				: $btcAddressMainnet) ?? ''
	);

	// BTC address generated by the ckBTC minter which needs to be used for BTC -> ckBTC conversion
	// Docs: https://github.com/dfinity/ic/blob/master/rs/bitcoin/ckbtc/minter/README.adoc#bitcoin-to-ckbtc
	let destinationAddress = $derived($btcAddressStore?.[$destinationToken.id]?.data);

	onMount(() => {
		loadBtcPendingSentTransactions({
			identity: $authIdentity,
			networkId,
			address: sourceAddress
		});
	});

	const convert = async () => {
		const network = nonNullish(networkId) ? mapNetworkIdToBitcoinNetwork(networkId) : undefined;

		if (isNullish($authIdentity)) {
			await nullishSignOut();
			return;
		}

		// The data has been already validated in the previous conversion flow steps.
		if (
			isNullish(network) ||
			isNullishOrEmpty(destinationAddress) ||
			invalidAmount(sendAmount) ||
			isNullish(sendAmount) ||
			isNullish($utxosFeeStore?.utxosFee)
		) {
			toastsError({
				msg: { text: $i18n.convert.error.unexpected_missing_data }
			});
			return;
		}

		onNext();

		try {
			await sendBtc({
				destination: destinationAddress,
				amount: sendAmount,
				utxosFee: $utxosFeeStore.utxosFee,
				network,
				source: sourceAddress,
				identity: $authIdentity,
				onProgress: () => {
					if (convertProgressStep === ProgressStepsConvert.INITIALIZATION) {
						progress(ProgressStepsConvert.CONVERT);
					} else if (convertProgressStep === ProgressStepsConvert.CONVERT) {
						progress(ProgressStepsConvert.UPDATE_UI);
					}
				}
			});

			progress(ProgressStepsConvert.DONE);

			trackEvent({
				name: TRACK_COUNT_CONVERT_BTC_TO_CKBTC_SUCCESS
			});

			setTimeout(() => close(), 750);
		} catch (err: unknown) {
			toastsError({
				msg: { text: $i18n.convert.error.unexpected },
				err
			});

			trackEvent({
				name: TRACK_COUNT_CONVERT_BTC_TO_CKBTC_ERROR
			});

			back();
		}
	};

	const close = () => onClose();
	const back = () => onBack();
</script>

<UtxosFeeContext amount={sendAmount} {amountError} {networkId} source={sourceAddress}>
	{#if currentStep?.name === WizardStepsConvert.CONVERT}
		<BtcConvertForm
			source={sourceAddress}
			on:icNext={onNext}
			on:icClose={onClose}
			bind:sendAmount
			bind:receiveAmount
			bind:amountError
		>
			{#snippet cancel()}
				{#if formCancelAction === 'back'}
					<ButtonBack onclick={back} />
				{:else}
					<ButtonCancel onclick={close} />
				{/if}
			{/snippet}
		</BtcConvertForm>
	{:else if currentStep?.name === WizardStepsConvert.REVIEW}
		<BtcConvertReview {receiveAmount} {sendAmount} on:icConvert={convert} on:icBack={onBack}>
			<ButtonBack slot="cancel" onclick={back} />
		</BtcConvertReview>
	{:else if currentStep?.name === WizardStepsConvert.CONVERTING}
		<BtcConvertProgress bind:convertProgressStep />
	{/if}
</UtxosFeeContext>
