export const ETHEREUM_EXPLORER_URL = import.meta.env.VITE_ETHEREUM_EXPLORER_URL;
export const CKBTC_EXPLORER_URL = import.meta.env.VITE_DASHBOARD_EXPLORER_CKBTC_URL;
export const CKETH_EXPLORER_URL = import.meta.env.VITE_DASHBOARD_EXPLORER_CKETH_URL;
