export const SWAP_SLIPPAGE_PRESET_VALUES = [0.5, 1.5, 3];
export const SWAP_DEFAULT_SLIPPAGE_VALUE = SWAP_SLIPPAGE_PRESET_VALUES[1];
export const SWAP_SLIPPAGE_VALUE_DECIMALS = 4;

export const SWAP_SLIPPAGE_WARNING_VALUE = 7;
export const SWAP_SLIPPAGE_INVALID_VALUE = 50;

export const SWAP_VALUE_DIFFERENCE_WARNING_VALUE = -1;
export const SWAP_VALUE_DIFFERENCE_ERROR_VALUE = -5;

export const SWAP_TOTAL_FEE_THRESHOLD = 0.01;
