#!/usr/bin/env bash
set -euo pipefail

NETWORK=ic
CANISTER=backend
OUTFILE="target/ic/candid/$CANISTER.$NETWORK.did"
[[ "${1:-}" != "--help" ]] || {
  cat <<-EOF
	Downloads the deployed $CANISTER API on the $NETWORK network to "$OUTFILE".
	EOF
  exit 1
}

DEPLOYED_COMMIT="$(dfx canister metadata "$CANISTER" git:commit --network "$NETWORK")"
DID_PATH="target/ic/candid/$CANISTER.$DEPLOYED_COMMIT.did"
mkdir -p "$(dirname "$DID_PATH")"
test -e "$DID_PATH" || dfx canister metadata "$CANISTER" candid:service --network "$NETWORK" >"$DID_PATH"
rm -f "$OUTFILE"
ln -s "$(basename "$DID_PATH")" "$OUTFILE"
