#!/usr/bin/env bash
set -euo pipefail
# Lint the Rust canister code, excluding the autogenerated crates.
for crate in src/backend/Cargo.toml src/shared/Cargo.toml; do
  cargo clippy --manifest-path "$crate" --locked --target wasm32-unknown-unknown --all-features -- -W deprecated
done
