#!/usr/bin/env bash
set -euo pipefail

FIX_ARGS=()

[[ "${1:-}" != "--help" ]] || {
  cat <<-EOF

	Usage: $0 [--fix]

	Options:
	  --fix     Apply automatic fixes with cargo clippy (allow dirty and staged).
	  --help    Show this help message and exit.

	EOF
  exit 0
}

if [[ "${1:-}" == "--fix" ]]; then
  FIX_ARGS+=(--fix --allow-dirty --allow-staged)
fi

# Lint the Rust canister code, excluding the autogenerated crates.
for crate in src/backend/Cargo.toml src/shared/Cargo.toml; do
  cargo clippy "${FIX_ARGS[@]}" \
    --manifest-path "$crate" \
    --locked \
    --target wasm32-unknown-unknown \
    --all-features
done
