#!/usr/bin/env bash
# Installs rust

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPTS_DIR/.."

function run() {
  echo 1>&2 "running $*"
  rc=0 && "$@" || rc="$?"
  if ! [ "$rc" -eq 0 ]; then
    echo 1>&2 "Bootstrap command failed: $*"
    exit "$rc"
  fi
}

NIGHTLY_VERSION="${version:-nightly}"
RUST_VERSION=$(sed -n 's/^channel[[:space:]]*=[[:space:]]"\(.*\)"/\1/p' rust-toolchain.toml)
echo "Using rust version '$RUST_VERSION' and nightly '$NIGHTLY_VERSION'"

RUSTUP_VERSION="$(jq -re .rustup.version dev-tools.json)"

# here we set the toolchain to 'none' and rustup will pick up on ./rust-toolchain.toml
run curl --fail "https://raw.githubusercontent.com/rust-lang/rustup/refs/tags/${RUSTUP_VERSION}/rustup-init.sh" -sSf | run sh -s -- -y --no-modify-path
rustup toolchain install            # Version from rust-toolchain.toml
rustup toolchain install "$version" # Version from dev-tools.json
rustup component add clippy
rustup component add rustfmt --toolchain "$NIGHTLY_VERSION"
rustup show

# make sure the packages are actually installed (rustup waits for the first invoke to lazyload)
cargo --version
cargo clippy --version
cargo +"$NIGHTLY_VERSION" fmt --version
