name: Deploy Backend

description: Build and deploy the backend after having installed dfx

# TODO: improve this action, caching the built Cargo packages, maybe with Docker

runs:
  using: 'composite'
  steps:
    - name: Restore cargo cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          /home/runner/.cargo/registry
          /home/runner/.cargo/git
          target/
          ~/.cargo/bin/
        key: ${{ runner.os }}-e2e-cargo-${{ hashFiles('Cargo.toml', 'Cargo.lock', 'rust-toolchain.toml', 'src/backend/**/*', 'src/shared/**/*') }}
        restore-keys: |
          ${{ runner.os }}-e2e-cargo-

    - name: Prepare
      uses: ./.github/actions/prepare

    - name: Install dfx
      uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365 # main

    - name: Start dfx
      shell: bash
      run: dfx start --background --quiet

    - name: Deploy backend
      shell: bash
      run: BACKEND_BUILD_STRATEGY=args npm run deploy
