name: 'Setup macOS'

description: 'Installs LLVM, coreutils and Bash 5 on macOS and sets up environment variables for wasm32 target'

runs:
  using: composite
  steps:
    - name: Install LLVM, coreutils and Bash on macOS
      shell: bash
      run: |
        brew install llvm
        brew install coreutils
        brew install bash

    - name: Add Bash 5 to PATH on macOS
      shell: bash
      run: |
        brew --prefix bash | awk '{print $0 "/bin"}' >> "$GITHUB_PATH"

    - name: Verify Bash Version
      shell: bash
      run: |
        bash --version

    - name: Set environment variables for wasm32 target on macOS
      shell: bash
      run: |
        {
          echo "CC_wasm32_unknown_unknown=$(brew --prefix llvm)/bin/clang"
          echo "AR_wasm32_unknown_unknown=$(brew --prefix llvm)/bin/llvm-ar"
          echo "CFLAGS_wasm32_unknown_unknown=--target=wasm32-unknown-unknown"
          echo "CRATE_CC_NO_DEFAULTS_wasm32_unknown_unknown=true"
        } >> "$GITHUB_ENV"
