/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const Value = IDL.Rec();
	const Vec = IDL.Rec();
	const AcceptDealArgs = IDL.Record({
		claim_code: IDL.Opt(IDL.Text),
		deal_id: IDL.Nat64
	});
	const DealStatus = IDL.Variant({
		Refunded: IDL.Null,
		Rejected: IDL.Null,
		Funded: IDL.Null,
		Cancelled: IDL.Null,
		Created: IDL.Null,
		Settled: IDL.Null
	});
	const Consent = IDL.Variant({
		Rejected: IDL.Null,
		Accepted: IDL.Null,
		Pending: IDL.Null
	});
	const DealView = IDL.Record({
		id: IDL.Nat64,
		status: DealStatus,
		title: IDL.Opt(IDL.Text),
		funded_at_ns: IDL.Opt(IDL.Nat64),
		updated_by: IDL.Opt(IDL.Principal),
		recipient_consent: Consent,
		refunded_at_ns: IDL.Opt(IDL.Nat64),
		note: IDL.Opt(IDL.Text),
		recipient: IDL.Opt(IDL.Principal),
		updated_at_ns: IDL.Opt(IDL.Nat64),
		escrow_subaccount: IDL.Vec(IDL.Nat8),
		created_by: IDL.Principal,
		payer_consent: Consent,
		created_at_ns: IDL.Nat64,
		claim_code: IDL.Opt(IDL.Text),
		settled_at_ns: IDL.Opt(IDL.Nat64),
		payer: IDL.Opt(IDL.Principal),
		amount: IDL.Nat,
		token_ledger: IDL.Principal,
		expires_at_ns: IDL.Nat64
	});
	const EscrowError = IDL.Variant({
		AlreadyFinalised: IDL.Null,
		SelfDeal: IDL.Null,
		NeitherPartySet: IDL.Null,
		InvalidExpiry: IDL.Null,
		AnonymousParty: IDL.Null,
		InvalidAmount: IDL.Null,
		PayerNotSet: IDL.Null,
		NotFound: IDL.Null,
		ValidationError: IDL.Text,
		NotAuthorised: IDL.Null,
		ConsentRequired: IDL.Null,
		MissingClaimCode: IDL.Null,
		LedgerError: IDL.Text,
		ExpiryTooFar: IDL.Null,
		ReliabilityTooLow: IDL.Record({
			threshold: IDL.Nat32,
			score: IDL.Nat32
		}),
		InvalidClaimCode: IDL.Null,
		MetadataTooLong: IDL.Record({ max: IDL.Nat32, field: IDL.Text }),
		RecipientMismatch: IDL.Null,
		TransferFailed: IDL.Text,
		TooManyActiveDeals: IDL.Record({ max: IDL.Nat32 }),
		NotExpired: IDL.Null,
		InvalidState: IDL.Record({ actual: IDL.Text, expected: IDL.Text }),
		Expired: IDL.Null
	});
	const AcceptDealResult = IDL.Variant({
		Ok: DealView,
		Err: EscrowError
	});
	const CancelDealArgs = IDL.Record({ deal_id: IDL.Nat64 });
	const CreateDealArgs = IDL.Record({
		title: IDL.Opt(IDL.Text),
		note: IDL.Opt(IDL.Text),
		recipient: IDL.Opt(IDL.Principal),
		payer: IDL.Opt(IDL.Principal),
		amount: IDL.Nat,
		token_ledger: IDL.Principal,
		expires_at_ns: IDL.Nat64
	});
	const FundDealArgs = IDL.Record({ deal_id: IDL.Nat64 });
	const FundDealResult = IDL.Variant({ Ok: DealView, Err: EscrowError });
	const ClaimableDealView = IDL.Record({
		id: IDL.Nat64,
		status: DealStatus,
		title: IDL.Opt(IDL.Text),
		note: IDL.Opt(IDL.Text),
		amount: IDL.Nat,
		token_ledger: IDL.Principal,
		expires_at_ns: IDL.Nat64,
		is_recipient_bound: IDL.Bool
	});
	const GetClaimableDealResult = IDL.Variant({
		Ok: ClaimableDealView,
		Err: EscrowError
	});
	const GetDealResult = IDL.Variant({ Ok: DealView, Err: EscrowError });
	const Account = IDL.Record({
		owner: IDL.Principal,
		subaccount: IDL.Opt(IDL.Vec(IDL.Nat8))
	});
	const GetEscrowAccountResult = IDL.Variant({
		Ok: Account,
		Err: EscrowError
	});
	const ReliabilityView = IDL.Record({
		concluded: IDL.Nat32,
		score: IDL.Opt(IDL.Nat32),
		positive: IDL.Nat32
	});
	const SupportedStandard = IDL.Record({ url: IDL.Text, name: IDL.Text });
	Vec.fill(
		IDL.Vec(
			IDL.Tuple(
				IDL.Text,
				IDL.Variant({
					Int: IDL.Int,
					Map: Vec,
					Nat: IDL.Nat,
					Blob: IDL.Vec(IDL.Nat8),
					Text: IDL.Text,
					Array: IDL.Vec(Value)
				})
			)
		)
	);
	Value.fill(
		IDL.Variant({
			Int: IDL.Int,
			Map: Vec,
			Nat: IDL.Nat,
			Blob: IDL.Vec(IDL.Nat8),
			Text: IDL.Text,
			Array: IDL.Vec(Value)
		})
	);
	const Icrc7TransferArg = IDL.Record({
		to: Account,
		token_id: IDL.Nat,
		memo: IDL.Opt(IDL.Vec(IDL.Nat8)),
		from_subaccount: IDL.Opt(IDL.Vec(IDL.Nat8)),
		created_at_time: IDL.Opt(IDL.Nat64)
	});
	const Icrc7TransferError = IDL.Variant({
		GenericError: IDL.Record({
			message: IDL.Text,
			error_code: IDL.Nat
		}),
		Duplicate: IDL.Record({ duplicate_of: IDL.Nat }),
		NonExistingTokenId: IDL.Null,
		Unauthorized: IDL.Null,
		CreatedInFuture: IDL.Record({ ledger_time: IDL.Nat64 }),
		InvalidRecipient: IDL.Null,
		GenericBatchError: IDL.Record({
			message: IDL.Text,
			error_code: IDL.Nat
		}),
		TooOld: IDL.Null
	});
	const Icrc7TransferResponse = IDL.Variant({
		Ok: IDL.Nat,
		Err: Icrc7TransferError
	});
	const ListMyDealsArgs = IDL.Record({
		offset: IDL.Opt(IDL.Nat64),
		limit: IDL.Opt(IDL.Nat64)
	});
	const ProcessExpiredDealsResult = IDL.Variant({
		Ok: IDL.Vec(IDL.Nat64),
		Err: EscrowError
	});

	return IDL.Service({
		accept_deal: IDL.Func([AcceptDealArgs], [AcceptDealResult], []),
		cancel_deal: IDL.Func([CancelDealArgs], [AcceptDealResult], []),
		config: IDL.Func([], [IDL.Record({})], ['query']),
		consent_deal: IDL.Func([CancelDealArgs], [AcceptDealResult], []),
		create_deal: IDL.Func([CreateDealArgs], [AcceptDealResult], []),
		fund_deal: IDL.Func([FundDealArgs], [FundDealResult], []),
		get_claimable_deal: IDL.Func([IDL.Nat64], [GetClaimableDealResult], ['query']),
		get_deal: IDL.Func([IDL.Nat64], [GetDealResult], ['query']),
		get_escrow_account: IDL.Func([IDL.Nat64], [GetEscrowAccountResult], ['query']),
		get_reliability: IDL.Func([IDL.Principal], [ReliabilityView], ['query']),
		icrc10_supported_standards: IDL.Func([], [IDL.Vec(SupportedStandard)], ['query']),
		icrc7_atomic_batch_transfers: IDL.Func([], [IDL.Opt(IDL.Bool)], ['query']),
		icrc7_balance_of: IDL.Func([IDL.Vec(Account)], [IDL.Vec(IDL.Nat)], ['query']),
		icrc7_collection_metadata: IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, Value))], ['query']),
		icrc7_default_take_value: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_description: IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
		icrc7_logo: IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
		icrc7_max_memo_size: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_max_query_batch_size: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_max_take_value: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_max_update_batch_size: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_name: IDL.Func([], [IDL.Text], ['query']),
		icrc7_owner_of: IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(IDL.Opt(Account))], ['query']),
		icrc7_permitted_drift: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_supply_cap: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_symbol: IDL.Func([], [IDL.Text], ['query']),
		icrc7_token_metadata: IDL.Func(
			[IDL.Vec(IDL.Nat)],
			[IDL.Vec(IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, Value))))],
			['query']
		),
		icrc7_tokens: IDL.Func([IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)], [IDL.Vec(IDL.Nat)], ['query']),
		icrc7_tokens_of: IDL.Func(
			[Account, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
			[IDL.Vec(IDL.Nat)],
			['query']
		),
		icrc7_total_supply: IDL.Func([], [IDL.Nat], ['query']),
		icrc7_transfer: IDL.Func(
			[IDL.Vec(Icrc7TransferArg)],
			[IDL.Vec(IDL.Opt(Icrc7TransferResponse))],
			[]
		),
		icrc7_tx_window: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		list_my_deals: IDL.Func([ListMyDealsArgs], [IDL.Vec(DealView)], ['query']),
		process_expired_deals: IDL.Func([IDL.Nat32], [ProcessExpiredDealsResult], []),
		reclaim_deal: IDL.Func([FundDealArgs], [GetDealResult], []),
		reject_deal: IDL.Func([FundDealArgs], [GetDealResult], []),
		update_config: IDL.Func([IDL.Record({})], [], [])
	});
};

export const init = ({ IDL }) => {
	return [];
};
