/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcceptDealArgs {
	claim_code: [] | [string];
	deal_id: bigint;
}
export type AcceptDealResult = { Ok: DealView } | { Err: EscrowError };
export interface Account {
	owner: Principal;
	subaccount: [] | [Uint8Array];
}
export interface CancelDealArgs {
	deal_id: bigint;
}
export interface ClaimableDealView {
	id: bigint;
	status: DealStatus;
	title: [] | [string];
	note: [] | [string];
	amount: bigint;
	token_ledger: Principal;
	expires_at_ns: bigint;
	is_recipient_bound: boolean;
}
export type Consent = { Rejected: null } | { Accepted: null } | { Pending: null };
export interface CreateDealArgs {
	title: [] | [string];
	note: [] | [string];
	recipient: [] | [Principal];
	payer: [] | [Principal];
	amount: bigint;
	token_ledger: Principal;
	expires_at_ns: bigint;
}
export type DealStatus =
	| { Refunded: null }
	| { Rejected: null }
	| { Funded: null }
	| { Cancelled: null }
	| { Created: null }
	| { Settled: null };
export interface DealView {
	id: bigint;
	status: DealStatus;
	title: [] | [string];
	funded_at_ns: [] | [bigint];
	updated_by: [] | [Principal];
	recipient_consent: Consent;
	refunded_at_ns: [] | [bigint];
	note: [] | [string];
	recipient: [] | [Principal];
	updated_at_ns: [] | [bigint];
	escrow_subaccount: Uint8Array;
	created_by: Principal;
	payer_consent: Consent;
	created_at_ns: bigint;
	claim_code: [] | [string];
	settled_at_ns: [] | [bigint];
	payer: [] | [Principal];
	amount: bigint;
	token_ledger: Principal;
	expires_at_ns: bigint;
}
export type EscrowError =
	| { AlreadyFinalised: null }
	| { SelfDeal: null }
	| { NeitherPartySet: null }
	| { InvalidExpiry: null }
	| { AnonymousParty: null }
	| { InvalidAmount: null }
	| { PayerNotSet: null }
	| { NotFound: null }
	| { ValidationError: string }
	| { NotAuthorised: null }
	| { ConsentRequired: null }
	| { MissingClaimCode: null }
	| { LedgerError: string }
	| { ExpiryTooFar: null }
	| { ReliabilityTooLow: { threshold: number; score: number } }
	| { InvalidClaimCode: null }
	| { MetadataTooLong: { max: number; field: string } }
	| { RecipientMismatch: null }
	| { TransferFailed: string }
	| { TooManyActiveDeals: { max: number } }
	| { NotExpired: null }
	| { InvalidState: { actual: string; expected: string } }
	| { Expired: null };
export interface FundDealArgs {
	deal_id: bigint;
}
export type FundDealResult = { Ok: DealView } | { Err: EscrowError };
export type GetClaimableDealResult = { Ok: ClaimableDealView } | { Err: EscrowError };
export type GetDealResult = { Ok: DealView } | { Err: EscrowError };
export type GetEscrowAccountResult = { Ok: Account } | { Err: EscrowError };
export interface Icrc7TransferArg {
	to: Account;
	token_id: bigint;
	memo: [] | [Uint8Array];
	from_subaccount: [] | [Uint8Array];
	created_at_time: [] | [bigint];
}
export type Icrc7TransferError =
	| {
			GenericError: { message: string; error_code: bigint };
	  }
	| { Duplicate: { duplicate_of: bigint } }
	| { NonExistingTokenId: null }
	| { Unauthorized: null }
	| { CreatedInFuture: { ledger_time: bigint } }
	| { InvalidRecipient: null }
	| { GenericBatchError: { message: string; error_code: bigint } }
	| { TooOld: null };
export type Icrc7TransferResponse = { Ok: bigint } | { Err: Icrc7TransferError };
export interface ListMyDealsArgs {
	offset: [] | [bigint];
	limit: [] | [bigint];
}
export type ProcessExpiredDealsResult = { Ok: BigUint64Array } | { Err: EscrowError };
export interface ReliabilityView {
	concluded: number;
	score: [] | [number];
	positive: number;
}
export interface SupportedStandard {
	url: string;
	name: string;
}
export type Value =
	| { Int: bigint }
	| { Map: Vec }
	| { Nat: bigint }
	| { Blob: Uint8Array }
	| { Text: string }
	| { Array: Array<Value> };
export type Vec = Array<
	[
		string,
		(
			| { Int: bigint }
			| { Map: Vec }
			| { Nat: bigint }
			| { Blob: Uint8Array }
			| { Text: string }
			| { Array: Array<Value> }
		)
	]
>;
export interface _SERVICE {
	/**
	 * Accepts (claims) a funded deal, releasing the escrowed tokens to the caller.
	 *
	 * If the deal has no bound recipient, the caller must supply the correct
	 * `claim_code`. The caller is bound as the recipient and their consent is
	 * automatically set to `Accepted`. The deal transitions from `Funded` to
	 * `Settled`.
	 */
	accept_deal: ActorMethod<[AcceptDealArgs], AcceptDealResult>;
	/**
	 * Cancels a deal that has not yet been funded.
	 *
	 * Either party may cancel. The deal transitions from `Created` to
	 * `Cancelled`. Funded deals cannot be cancelled — use [`reclaim_deal`] after
	 * expiry instead.
	 */
	cancel_deal: ActorMethod<[CancelDealArgs], AcceptDealResult>;
	/**
	 * Returns the current global configuration of the Escrow canister.
	 *
	 * This method is gated to canister controllers.
	 */
	config: ActorMethod<[], {}>;
	/**
	 * Explicitly consents to a deal's terms.
	 *
	 * The caller must be the payer or recipient. Sets their consent to `Accepted`.
	 * Both parties must consent before the payer can fund a deal with a known
	 * recipient.
	 */
	consent_deal: ActorMethod<[CancelDealArgs], AcceptDealResult>;
	/**
	 * Creates a new escrow deal.
	 *
	 * The caller is automatically assigned as one of the parties based on the
	 * supplied `payer` and `recipient` fields. Their consent is set to `Accepted`;
	 * the counterparty's consent starts as `Pending`.
	 *
	 * A cryptographically random claim code is generated and returned in the
	 * `DealView`. This code must be included in QR / share links so that an
	 * unbound recipient can later claim the deal.
	 */
	create_deal: ActorMethod<[CreateDealArgs], AcceptDealResult>;
	/**
	 * Funds a previously created deal by transferring tokens from the payer's
	 * account into the deal's escrow subaccount via ICRC-2 `transfer_from`.
	 *
	 * The deal transitions from `Created` to `Funded`. Funding implicitly sets
	 * the payer's consent to `Accepted`. For deals with a known recipient, the
	 * recipient must have consented first.
	 */
	fund_deal: ActorMethod<[FundDealArgs], FundDealResult>;
	/**
	 * Reduced public view for claim/share-link pages.
	 * Returns limited info (no payer, no claim code, no internal fields). Any
	 * authenticated caller may query this — authorization is intentionally open
	 * so a not-yet-bound recipient can preview the deal before accepting.
	 */
	get_claimable_deal: ActorMethod<[bigint], GetClaimableDealResult>;
	/**
	 * Returns the full deal view for an authorised participant.
	 *
	 * Only the payer or the bound recipient may query a deal's full details.
	 */
	get_deal: ActorMethod<[bigint], GetDealResult>;
	/**
	 * Returns the escrow `Account` (canister principal + deal subaccount) for a deal.
	 */
	get_escrow_account: ActorMethod<[bigint], GetEscrowAccountResult>;
	/**
	 * Returns the reliability score for any principal.
	 *
	 * This is a public query — any authenticated caller may check any
	 * principal's score. No authorization required beyond being non-anonymous.
	 */
	get_reliability: ActorMethod<[Principal], ReliabilityView>;
	/**
	 * Returns the list of ICRC standards supported by this canister.
	 *
	 * Currently reports ICRC-7 (NFT) and ICRC-10 (supported-standards discovery).
	 */
	icrc10_supported_standards: ActorMethod<[], Array<SupportedStandard>>;
	/**
	 * Whether batch transfers are executed atomically. Currently `None`.
	 */
	icrc7_atomic_batch_transfers: ActorMethod<[], [] | [boolean]>;
	/**
	 * Returns the number of deal NFTs owned by each requested account.
	 *
	 * Accounts with a non-default subaccount always return `0`.
	 */
	icrc7_balance_of: ActorMethod<[Array<Account>], Array<bigint>>;
	/**
	 * Returns collection-level metadata as an ICRC-16 key-value map.
	 *
	 * Includes `icrc7:name`, `icrc7:symbol`, `icrc7:description`, and
	 * `icrc7:total_supply`.
	 */
	icrc7_collection_metadata: ActorMethod<[], Array<[string, Value]>>;
	/**
	 * Returns the default page size for `icrc7_tokens` / `icrc7_tokens_of`
	 * when the caller omits the `take` argument.
	 */
	icrc7_default_take_value: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns a human-readable description of the NFT collection.
	 */
	icrc7_description: ActorMethod<[], [] | [string]>;
	/**
	 * Returns the collection logo. Currently `None`.
	 */
	icrc7_logo: ActorMethod<[], [] | [string]>;
	/**
	 * Returns the maximum memo size accepted in transfer arguments.
	 *
	 * Currently `None` (no explicit limit).
	 */
	icrc7_max_memo_size: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the maximum number of token IDs accepted by `icrc7_token_metadata`
	 * and `icrc7_owner_of` in a single call.
	 */
	icrc7_max_query_batch_size: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the maximum page size for `icrc7_tokens` / `icrc7_tokens_of`.
	 */
	icrc7_max_take_value: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the maximum number of transfer args accepted by `icrc7_transfer`
	 * in a single call. Currently `None`.
	 */
	icrc7_max_update_batch_size: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the human-readable name of the NFT collection (`"Escrow Deals"`).
	 */
	icrc7_name: ActorMethod<[], string>;
	/**
	 * Returns the owner account for each requested token ID.
	 *
	 * Ownership follows deal lifecycle: the payer owns the token in all states
	 * except `Settled`, where the recipient becomes the owner.
	 * Unknown IDs produce `None`.
	 */
	icrc7_owner_of: ActorMethod<[Array<bigint>], Array<[] | [Account]>>;
	/**
	 * Returns the permitted time drift for deduplication. Currently `None`.
	 */
	icrc7_permitted_drift: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the maximum number of deal NFTs that can ever exist.
	 *
	 * Currently `None` (unlimited).
	 */
	icrc7_supply_cap: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the ticker symbol of the NFT collection (`"ESCROW"`).
	 */
	icrc7_symbol: ActorMethod<[], string>;
	/**
	 * Returns per-token metadata for each requested token ID.
	 *
	 * Each deal's metadata includes `icrc7:name`, `escrow:status`,
	 * `escrow:payer`, `escrow:amount`, `escrow:token_ledger`, and other
	 * deal-specific fields. Unknown IDs produce `None` in the result vector.
	 */
	icrc7_token_metadata: ActorMethod<[Array<bigint>], Array<[] | [Array<[string, Value]>]>>;
	/**
	 * Returns a page of token IDs in ascending order.
	 *
	 * `prev` is the last token ID the caller received (exclusive cursor).
	 * `take` limits the page size (defaults to 50, capped at 500).
	 */
	icrc7_tokens: ActorMethod<[[] | [bigint], [] | [bigint]], Array<bigint>>;
	/**
	 * Returns a page of token IDs owned by `account`, in ascending order.
	 *
	 * See [`icrc7_tokens`] for cursor / take semantics.
	 */
	icrc7_tokens_of: ActorMethod<[Account, [] | [bigint], [] | [bigint]], Array<bigint>>;
	/**
	 * Returns the total number of deal NFTs that have been minted (one per deal).
	 */
	icrc7_total_supply: ActorMethod<[], bigint>;
	/**
	 * Rejects all transfer attempts with a `GenericError`.
	 *
	 * Deal ownership transitions are managed exclusively through escrow
	 * operations (`accept_deal`, `reclaim_deal`, …), not via direct ICRC-7
	 * transfers.
	 */
	icrc7_transfer: ActorMethod<[Array<Icrc7TransferArg>], Array<[] | [Icrc7TransferResponse]>>;
	/**
	 * Returns the transaction deduplication window. Currently `None`.
	 */
	icrc7_tx_window: ActorMethod<[], [] | [bigint]>;
	/**
	 * Lists all deals where the caller is either the payer or the recipient,
	 * ordered by creation time with pagination support.
	 */
	list_my_deals: ActorMethod<[ListMyDealsArgs], Array<DealView>>;
	/**
	 * Batch-processes expired deals by refunding escrowed tokens back to their
	 * payers.
	 *
	 * Scans up to `limit` expired-but-still-funded deals and attempts to reclaim
	 * each one. Returns the IDs of deals that were successfully refunded.
	 */
	process_expired_deals: ActorMethod<[number], ProcessExpiredDealsResult>;
	/**
	 * Reclaims escrowed funds from an expired, unclaimed deal back to the payer.
	 *
	 * Only callable after the deal's `expires_at_ns` deadline has passed. The deal
	 * transitions from `Funded` to `Refunded`.
	 */
	reclaim_deal: ActorMethod<[FundDealArgs], GetDealResult>;
	/**
	 * Rejects a deal's terms. The deal transitions to `Rejected` (terminal).
	 *
	 * The caller must be the payer or recipient. Their consent is set to
	 * `Rejected` and the deal becomes final.
	 */
	reject_deal: ActorMethod<[FundDealArgs], GetDealResult>;
	/**
	 * Updates the global configuration for the Escrow canister.
	 *
	 * This method is gated to canister controllers.
	 */
	update_config: ActorMethod<[{}], undefined>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
