/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

/**
 * HttpRequest related types
 */
export type HeaderField = [string, string];
export interface HttpRequest {
	url: string;
	method: string;
	body: Uint8Array;
	headers: Array<HeaderField>;
}
export interface HttpResponse {
	body: Uint8Array;
	headers: Array<HeaderField>;
	status_code: number;
}
export interface ICPTs {
	e8s: bigint;
}
export interface Listing {
	tokenId: bigint;
	owner: Principal;
	timestamp: Time;
	price: bigint;
}
export interface MintRequest {
	url: string;
	contentType: string;
	owner: Principal;
	data: Uint8Array;
	desc: string;
	name: string;
	properties: Array<Property>;
}
export interface Property {
	value: string;
	name: string;
}
export type Result = { Ok: string } | { Err: string };
export interface StreamingCallbackHttpResponse {
	token: [] | [Token];
	body: Uint8Array;
}
export type StreamingStrategy = {
	Callback: { token: Token; callback: [Principal, string] };
};
export type Time = bigint;
export type Token = {};
export interface TokenDesc {
	id: bigint;
	url: string;
	owner: Principal;
	desc: string;
	name: string;
	properties: Array<Property>;
}
export interface TransactionNotification {
	to: Principal;
	to_subaccount: [] | [number];
	from: Principal;
	memo: bigint;
	from_subaccount: [] | [number];
	amount: ICPTs;
	block_height: bigint;
}
export interface TransferRequest {
	to: Principal;
	token_id: bigint;
}
export interface _SERVICE {
	add_genesis_record: ActorMethod<[], bigint>;
	creators_fee: ActorMethod<[], bigint>;
	data_of: ActorMethod<[bigint], TokenDesc>;
	delist: ActorMethod<[bigint], boolean>;
	description: ActorMethod<[], string>;
	get_cycles: ActorMethod<[], bigint>;
	get_ledger_canister: ActorMethod<[], Principal>;
	get_listed: ActorMethod<[bigint], Array<Listing>>;
	get_listed_count: ActorMethod<[], bigint>;
	get_storage_canister: ActorMethod<[], Principal>;
	http_request: ActorMethod<[HttpRequest], HttpResponse>;
	icon_url: ActorMethod<[], string>;
	list: ActorMethod<[bigint, bigint], boolean>;
	mint: ActorMethod<[MintRequest], bigint>;
	multi_mint: ActorMethod<[Array<MintRequest>], Array<bigint>>;
	multi_transfer_to: ActorMethod<[Array<TransferRequest>], Array<boolean>>;
	name: ActorMethod<[], string>;
	owner: ActorMethod<[], Principal>;
	owner_of: ActorMethod<[bigint], Principal>;
	set_description: ActorMethod<[string], boolean>;
	set_icon_url: ActorMethod<[string], boolean>;
	set_ledger_canister: ActorMethod<[Principal], boolean>;
	set_owner: ActorMethod<[Principal], boolean>;
	set_storage_canister: ActorMethod<[Principal], boolean>;
	set_tx_enabled: ActorMethod<[boolean], boolean>;
	symbol: ActorMethod<[], string>;
	total_supply: ActorMethod<[], bigint>;
	transaction_notification: ActorMethod<[TransactionNotification], Result>;
	transfer_to: ActorMethod<[Principal, bigint], boolean>;
	tx_enabled: ActorMethod<[], boolean>;
	user_tokens: ActorMethod<[Principal], Array<bigint>>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
