name: Backend Checks

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check if backend files changed
        id: changes
        uses: ./.github/actions/check-backend-changes
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: steps.changes.outputs.backend == 'true'
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-backend-tests-${{ hashFiles('Cargo.lock', 'rust-toolchain.toml') }}
      - name: Install rust
        if: steps.changes.outputs.backend == 'true'
        run: ./scripts/setup rust
      - name: Lint rust
        if: steps.changes.outputs.backend == 'true'
        run: ./scripts/lint.rust.sh
      - name: Lint candid
        if: steps.changes.outputs.backend == 'true'
        run: ./scripts/lint.did.sh

  workspace-dependencies:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check if backend files changed
        id: changes
        uses: ./.github/actions/check-backend-changes
      - name: Install yq
        if: steps.changes.outputs.backend == 'true'
        run: sudo snap install yq
      - name: Dependencies are defined in the workspace
        if: steps.changes.outputs.backend == 'true'
        run: ./scripts/lint.cargo-workspace-dependencies.sh

  backend-checks-pass:
    needs: ['lint', 'workspace-dependencies']
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/needs_success
        with:
          needs: '${{ toJson(needs) }}'
