name: E2E Tests

on:
  pull_request:
    paths:
      - 'e2e/**'
  workflow_dispatch:

env:
  RUNNER_OS: ubuntu-20.04
  IMAGE_NAME: oisy-e2e-image
  CONTAINER_NAME: oisy-e2e-container

jobs:

  docker-build-e2e:
    runs-on: ${{ env.RUNNER_OS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Base Docker Image
        uses: ./.github/actions/docker-build-e2e
        with:
          name: ${{ env.IMAGE_NAME }}

  e2e:
    runs-on: ubuntu-latest
    needs: docker-build-e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: .

      - name: Load Docker image
        run: |
          gzip -d ${{ env.IMAGE_NAME }}.gz
          docker load -i ${{ env.IMAGE_NAME }}.tar

      - name: Run Docker container
        run: |
          docker run -d --name ${{ env.CONTAINER_NAME }} ${{ env.IMAGE_NAME }}:latest

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Test
        run: npm run test

      - name: Cleanup Docker container
        run: |
          docker stop ${{ env.CONTAINER_NAME }}
          docker rm ${{ env.CONTAINER_NAME }}

  may-merge:
    needs: ['e2e']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
