# A GitHub Actions workflow that can be used to trigger updates of npm packages.
name: Update npm Package Dependencies

on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        type: choice
        description: 'Select the package(s) to update.'
        options:
          - gix-components
          - ic-js
          - oisy-wallet-signer
          - eslint-config-oisy-wallet
          - agent
          - agent & ic-js
      next:
        required: false
        type: boolean
        description: 'Update all dependencies to the next version'
        default: true

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: ${{ vars.PR_AUTOMATION_BOT_PUBLIC_APP_ID }}
          private-key: ${{ secrets.PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Set package variable
        id: package_name
        run: |
          case "$PACKAGE" in
            "gix-components") PKG_NAME="gix-cmp" ;;
            "ic-js") PKG_NAME="ic-js" ;;
            "oisy-wallet-signer") PKG_NAME="signer" ;;
            "eslint-config-oisy-wallet") PKG_NAME="oisy-eslint" ;;
            "agent") PKG_NAME="agent" ;;
            "agent & ic-js") PKG_NAME="agent:ic-js" ;;
            *) echo "Invalid package selection: $PACKAGE" && exit 1 ;;
          esac
          echo "PKG_NAME=$PKG_NAME" >> "$GITHUB_ENV"
        env:
          PACKAGE: ${{ inputs.package }}

      - name: Update package
        run: npm run update:${{ env.PKG_NAME }}${{ inputs.next && ':next' || '' }}

      - name: Create Pull Request
        uses: ./.github/actions/create-pr
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: bot-bump-${{ inputs.package }}${{ inputs.next && '-next' || '' }}
          title: "build(frontend): Bump ${{ inputs.package }}${{ inputs.next && ' to next' || '' }}"
          body: |
            # Motivation

            We want to pull in the latest changes for the `${{ inputs.package }}` package.

            # Changes

            * Ran `npm run update:${{ env.PKG_NAME }}${{ inputs.next && ':next' || '' }}`

            # Tests

            * CI should pass
            * The pulled in changes should have been tested before being committed to their repositories.
