# A GitHub Actions workflow that can be used to trigger updates of npm packages.
name: Update npm package dependencies

on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        type: choice
        description: 'Select the package(s) to update.'
        options:
          - gix-components
          - ic-js
          - oisy-wallet-signer
          - agent
          - agent & ic-js
      next:
        required: false
        type: boolean
        description: 'Update all dependencies to the next version'
        default: true

jobs:
  update-next-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PR_AUTOMATION_BOT_PUBLIC_APP_ID }}
          private-key: ${{ secrets.PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY }}

      - name: Checkout code
        if: steps.check_can_add_commit.outputs.can_add_commit == 'false'
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Set package variable
        id: package_name
        run: |
          case "${{ inputs.package }}" in
            "gix-components") echo "PKG_NAME=gix-cmp" >> "$GITHUB_ENV" ;;
            "ic-js") echo "PKG_NAME=ic-js" >> "$GITHUB_ENV" ;;
            "oisy-wallet-signer") echo "PKG_NAME=signer" >> "$GITHUB_ENV" ;;
            "agent") echo "PKG_NAME=agent" >> "$GITHUB_ENV" ;;
            "agent & ic-js") echo "PKG_NAME=agent:ic-js" >> "$GITHUB_ENV" ;;
            *) echo "Invalid package selection" && exit 1 ;;
          esac

      - name: Update package
        run: npm run update:${{ env.PKG_NAME }}${{ inputs.next && ':next' || '' }}

      - name: Create Pull Request
        uses: ./.github/actions/create-pr
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: bot-bump-next
          title: "build(frontend): Bump ${{ inputs.gix_components && 'gix-components' || '' }}${{ inputs.gix_components && inputs.ic_js && ' and ' || '' }}${{ inputs.ic_js && 'ic-js' || '' }}"
          body: |
            # Motivation
            
            We want to pull in the latest changes for the ${{ inputs.package }} package.
            
            # Changes
            
            * Ran `npm run update:${{ inputs.package }}${{ inputs.next && ':next' || '' }}`
            
            # Tests
            
            * CI should pass
            * The pulled in changes should have been tested before being committed to their repositories.

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Bump
          committer: GitHub <noreply@github.com>
          author: gix-bot <gix-bot@users.noreply.github.com>
          branch: bot-bump-next
          branch-suffix: timestamp
          reviewers: mstrasinskis, dskloetd, yhabib
          add-paths: |
            frontend
          delete-branch: true
          title: "bot: Bump ${{ inputs.gix_components && 'gix-components' || '' }}${{ inputs.gix_components && inputs.ic_js && ' and ' || '' }}${{ inputs.ic_js && 'ic-js' || '' }}"
          body: |
            # Motivation

            We want to pull in the latest changes.
            This PR was requested by ${{ github.actor }}.

            # Changes

            ${{ inputs.gix_components && '* Ran `npm run update:gix-cmps`' || '' }}
            ${{ inputs.ic_js && '* Ran `npm run update:ic-js`' || '' }}

            # Tests

            * CI should pass
            * The pulled in changes should have been tested before being committed to their repositories.
